#
# Module manifest for module 'Microsoft.Graph.Files'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/26/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Files.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '45ddab16-496a-4ef0-ac17-dbf0f93494d3'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.2.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Files.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Files.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgDriveListContentTypeCopy', 
               'Add-MgDriveListContentTypeCopyFromContentTypeHub', 
               'Add-MgShareListContentTypeCopy', 
               'Add-MgShareListContentTypeCopyFromContentTypeHub', 
               'Copy-MgDriveItem', 
               'Copy-MgDriveListContentTypeToDefaultContentLocation', 
               'Copy-MgDriveRoot', 
               'Copy-MgShareListContentTypeToDefaultContentLocation', 
               'Get-MgDrive', 'Get-MgDriveBundle', 'Get-MgDriveBundleContent', 
               'Get-MgDriveBundleCount', 'Get-MgDriveContentTypeBase', 
               'Get-MgDriveContentTypeBaseType', 
               'Get-MgDriveContentTypeBaseTypeCount', 'Get-MgDriveCreatedByUser', 
               'Get-MgDriveCreatedByUserMailboxSetting', 'Get-MgDriveFollowing', 
               'Get-MgDriveFollowingContent', 'Get-MgDriveFollowingCount', 
               'Get-MgDriveItem', 'Get-MgDriveItemActivityByInterval', 
               'Get-MgDriveItemAnalytic', 
               'Get-MgDriveItemAnalyticItemActivityStat', 
               'Get-MgDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgDriveItemAnalyticItemActivityStatCount', 
               'Get-MgDriveItemAnalyticLastSevenDay', 
               'Get-MgDriveItemAnalyticTime', 'Get-MgDriveItemChild', 
               'Get-MgDriveItemChildContent', 'Get-MgDriveItemChildCount', 
               'Get-MgDriveItemContent', 'Get-MgDriveItemCount', 
               'Get-MgDriveItemCreatedByUser', 
               'Get-MgDriveItemCreatedByUserMailboxSetting', 
               'Get-MgDriveItemDelta', 'Get-MgDriveItemItemLastModifiedByUser', 
               'Get-MgDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgDriveItemLastModifiedByUser', 
               'Get-MgDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgDriveItemListItem', 
               'Get-MgDriveItemListItemActivityByInterval', 
               'Get-MgDriveItemListItemAnalytic', 
               'Get-MgDriveItemListItemCreatedByUser', 
               'Get-MgDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgDriveItemListItemDocumentSetVersion', 
               'Get-MgDriveItemListItemDocumentSetVersionCount', 
               'Get-MgDriveItemListItemDocumentSetVersionField', 
               'Get-MgDriveItemListItemDriveItem', 
               'Get-MgDriveItemListItemDriveItemContent', 
               'Get-MgDriveItemListItemField', 'Get-MgDriveItemListItemVersion', 
               'Get-MgDriveItemListItemVersionCount', 
               'Get-MgDriveItemListItemVersionField', 'Get-MgDriveItemPermission', 
               'Get-MgDriveItemPermissionCount', 'Get-MgDriveItemSubscription', 
               'Get-MgDriveItemSubscriptionCount', 'Get-MgDriveItemThumbnail', 
               'Get-MgDriveItemThumbnailCount', 'Get-MgDriveItemVersion', 
               'Get-MgDriveItemVersionContent', 'Get-MgDriveItemVersionCount', 
               'Get-MgDriveLastModifiedByUser', 
               'Get-MgDriveLastModifiedByUserMailboxSetting', 'Get-MgDriveList', 
               'Get-MgDriveListColumn', 'Get-MgDriveListColumnCount', 
               'Get-MgDriveListColumnSourceColumn', 'Get-MgDriveListContentType', 
               'Get-MgDriveListContentTypeColumn', 
               'Get-MgDriveListContentTypeColumnCount', 
               'Get-MgDriveListContentTypeColumnLink', 
               'Get-MgDriveListContentTypeColumnLinkCount', 
               'Get-MgDriveListContentTypeColumnPosition', 
               'Get-MgDriveListContentTypeColumnPositionCount', 
               'Get-MgDriveListContentTypeColumnSourceColumn', 
               'Get-MgDriveListContentTypeCompatibleHubContentType', 
               'Get-MgDriveListContentTypeCount', 'Get-MgDriveListCreatedByUser', 
               'Get-MgDriveListCreatedByUserMailboxSetting', 
               'Get-MgDriveListDrive', 'Get-MgDriveListItem', 
               'Get-MgDriveListItemActivityByInterval', 
               'Get-MgDriveListItemAnalytic', 'Get-MgDriveListItemCount', 
               'Get-MgDriveListItemCreatedByUser', 
               'Get-MgDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgDriveListItemDocumentSetVersion', 
               'Get-MgDriveListItemDocumentSetVersionCount', 
               'Get-MgDriveListItemDocumentSetVersionField', 
               'Get-MgDriveListItemDriveItem', 
               'Get-MgDriveListItemDriveItemContent', 'Get-MgDriveListItemField', 
               'Get-MgDriveListItemVersion', 'Get-MgDriveListItemVersionCount', 
               'Get-MgDriveListItemVersionField', 'Get-MgDriveListOperation', 
               'Get-MgDriveListOperationCount', 'Get-MgDriveListSubscription', 
               'Get-MgDriveListSubscriptionCount', 'Get-MgDriveRoot', 
               'Get-MgDriveRootActivityByInterval', 'Get-MgDriveRootAnalytic', 
               'Get-MgDriveRootAnalyticItemActivityStat', 
               'Get-MgDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgDriveRootAnalyticItemActivityStatCount', 
               'Get-MgDriveRootAnalyticLastSevenDay', 
               'Get-MgDriveRootAnalyticTime', 'Get-MgDriveRootChild', 
               'Get-MgDriveRootChildContent', 'Get-MgDriveRootChildCount', 
               'Get-MgDriveRootContent', 'Get-MgDriveRootCreatedByUser', 
               'Get-MgDriveRootCreatedByUserMailboxSetting', 
               'Get-MgDriveRootDelta', 'Get-MgDriveRootItemLastModifiedByUser', 
               'Get-MgDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgDriveRootLastModifiedByUser', 
               'Get-MgDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgDriveRootListItem', 
               'Get-MgDriveRootListItemActivityByInterval', 
               'Get-MgDriveRootListItemAnalytic', 
               'Get-MgDriveRootListItemCreatedByUser', 
               'Get-MgDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgDriveRootListItemDocumentSetVersion', 
               'Get-MgDriveRootListItemDocumentSetVersionCount', 
               'Get-MgDriveRootListItemDocumentSetVersionField', 
               'Get-MgDriveRootListItemDriveItem', 
               'Get-MgDriveRootListItemDriveItemContent', 
               'Get-MgDriveRootListItemField', 'Get-MgDriveRootListItemVersion', 
               'Get-MgDriveRootListItemVersionCount', 
               'Get-MgDriveRootListItemVersionField', 'Get-MgDriveRootPermission', 
               'Get-MgDriveRootPermissionCount', 'Get-MgDriveRootSubscription', 
               'Get-MgDriveRootSubscriptionCount', 'Get-MgDriveRootThumbnail', 
               'Get-MgDriveRootThumbnailCount', 'Get-MgDriveRootVersion', 
               'Get-MgDriveRootVersionContent', 'Get-MgDriveRootVersionCount', 
               'Get-MgDriveSpecial', 'Get-MgDriveSpecialContent', 
               'Get-MgDriveSpecialCount', 'Get-MgGroupDefaultDrive', 
               'Get-MgGroupDrive', 'Get-MgGroupDriveBundle', 
               'Get-MgGroupDriveBundleContent', 'Get-MgGroupDriveBundleCount', 
               'Get-MgGroupDriveContentTypeBase', 
               'Get-MgGroupDriveContentTypeBaseType', 
               'Get-MgGroupDriveContentTypeBaseTypeCount', 'Get-MgGroupDriveCount', 
               'Get-MgGroupDriveCreatedByUser', 
               'Get-MgGroupDriveCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveFollowing', 'Get-MgGroupDriveFollowingContent', 
               'Get-MgGroupDriveFollowingCount', 'Get-MgGroupDriveItem', 
               'Get-MgGroupDriveItemAnalytic', 
               'Get-MgGroupDriveItemAnalyticItemActivityStat', 
               'Get-MgGroupDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgGroupDriveItemAnalyticItemActivityStatCount', 
               'Get-MgGroupDriveItemAnalyticLastSevenDay', 
               'Get-MgGroupDriveItemAnalyticTime', 'Get-MgGroupDriveItemChild', 
               'Get-MgGroupDriveItemChildContent', 
               'Get-MgGroupDriveItemChildCount', 'Get-MgGroupDriveItemContent', 
               'Get-MgGroupDriveItemCount', 'Get-MgGroupDriveItemCreatedByUser', 
               'Get-MgGroupDriveItemCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveItemItemLastModifiedByUser', 
               'Get-MgGroupDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgGroupDriveItemLastModifiedByUser', 
               'Get-MgGroupDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgGroupDriveItemListItem', 
               'Get-MgGroupDriveItemListItemAnalytic', 
               'Get-MgGroupDriveItemListItemCreatedByUser', 
               'Get-MgGroupDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveItemListItemDocumentSetVersion', 
               'Get-MgGroupDriveItemListItemDocumentSetVersionCount', 
               'Get-MgGroupDriveItemListItemDocumentSetVersionField', 
               'Get-MgGroupDriveItemListItemDriveItem', 
               'Get-MgGroupDriveItemListItemDriveItemContent', 
               'Get-MgGroupDriveItemListItemField', 
               'Get-MgGroupDriveItemListItemVersion', 
               'Get-MgGroupDriveItemListItemVersionCount', 
               'Get-MgGroupDriveItemListItemVersionField', 
               'Get-MgGroupDriveItemPermission', 
               'Get-MgGroupDriveItemPermissionCount', 
               'Get-MgGroupDriveItemSubscription', 
               'Get-MgGroupDriveItemSubscriptionCount', 
               'Get-MgGroupDriveItemThumbnail', 
               'Get-MgGroupDriveItemThumbnailCount', 'Get-MgGroupDriveItemVersion', 
               'Get-MgGroupDriveItemVersionContent', 
               'Get-MgGroupDriveItemVersionCount', 
               'Get-MgGroupDriveLastModifiedByUser', 
               'Get-MgGroupDriveLastModifiedByUserMailboxSetting', 
               'Get-MgGroupDriveList', 'Get-MgGroupDriveListColumn', 
               'Get-MgGroupDriveListColumnCount', 
               'Get-MgGroupDriveListColumnSourceColumn', 
               'Get-MgGroupDriveListContentType', 
               'Get-MgGroupDriveListContentTypeColumn', 
               'Get-MgGroupDriveListContentTypeColumnCount', 
               'Get-MgGroupDriveListContentTypeColumnLink', 
               'Get-MgGroupDriveListContentTypeColumnLinkCount', 
               'Get-MgGroupDriveListContentTypeColumnPosition', 
               'Get-MgGroupDriveListContentTypeColumnPositionCount', 
               'Get-MgGroupDriveListContentTypeColumnSourceColumn', 
               'Get-MgGroupDriveListContentTypeCount', 
               'Get-MgGroupDriveListCreatedByUser', 
               'Get-MgGroupDriveListCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveListDrive', 'Get-MgGroupDriveListItem', 
               'Get-MgGroupDriveListItemAnalytic', 
               'Get-MgGroupDriveListItemCreatedByUser', 
               'Get-MgGroupDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveListItemDocumentSetVersion', 
               'Get-MgGroupDriveListItemDocumentSetVersionCount', 
               'Get-MgGroupDriveListItemDocumentSetVersionField', 
               'Get-MgGroupDriveListItemDriveItem', 
               'Get-MgGroupDriveListItemDriveItemContent', 
               'Get-MgGroupDriveListItemField', 'Get-MgGroupDriveListItemVersion', 
               'Get-MgGroupDriveListItemVersionCount', 
               'Get-MgGroupDriveListItemVersionField', 
               'Get-MgGroupDriveListOperation', 
               'Get-MgGroupDriveListOperationCount', 
               'Get-MgGroupDriveListSubscription', 
               'Get-MgGroupDriveListSubscriptionCount', 'Get-MgGroupDriveRoot', 
               'Get-MgGroupDriveRootAnalytic', 
               'Get-MgGroupDriveRootAnalyticItemActivityStat', 
               'Get-MgGroupDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgGroupDriveRootAnalyticItemActivityStatCount', 
               'Get-MgGroupDriveRootAnalyticLastSevenDay', 
               'Get-MgGroupDriveRootAnalyticTime', 'Get-MgGroupDriveRootChild', 
               'Get-MgGroupDriveRootChildContent', 
               'Get-MgGroupDriveRootChildCount', 'Get-MgGroupDriveRootContent', 
               'Get-MgGroupDriveRootCreatedByUser', 
               'Get-MgGroupDriveRootCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveRootItemLastModifiedByUser', 
               'Get-MgGroupDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgGroupDriveRootLastModifiedByUser', 
               'Get-MgGroupDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgGroupDriveRootListItem', 
               'Get-MgGroupDriveRootListItemAnalytic', 
               'Get-MgGroupDriveRootListItemCreatedByUser', 
               'Get-MgGroupDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgGroupDriveRootListItemDocumentSetVersion', 
               'Get-MgGroupDriveRootListItemDocumentSetVersionCount', 
               'Get-MgGroupDriveRootListItemDocumentSetVersionField', 
               'Get-MgGroupDriveRootListItemDriveItem', 
               'Get-MgGroupDriveRootListItemDriveItemContent', 
               'Get-MgGroupDriveRootListItemField', 
               'Get-MgGroupDriveRootListItemVersion', 
               'Get-MgGroupDriveRootListItemVersionCount', 
               'Get-MgGroupDriveRootListItemVersionField', 
               'Get-MgGroupDriveRootPermission', 
               'Get-MgGroupDriveRootPermissionCount', 
               'Get-MgGroupDriveRootSubscription', 
               'Get-MgGroupDriveRootSubscriptionCount', 
               'Get-MgGroupDriveRootThumbnail', 
               'Get-MgGroupDriveRootThumbnailCount', 'Get-MgGroupDriveRootVersion', 
               'Get-MgGroupDriveRootVersionContent', 
               'Get-MgGroupDriveRootVersionCount', 'Get-MgGroupDriveSpecial', 
               'Get-MgGroupDriveSpecialContent', 'Get-MgGroupDriveSpecialCount', 
               'Get-MgShareContentTypeBase', 'Get-MgShareContentTypeBaseType', 
               'Get-MgShareContentTypeBaseTypeCount', 'Get-MgShareCount', 
               'Get-MgShareCreatedByUser', 
               'Get-MgShareCreatedByUserMailboxSetting', 'Get-MgShareDriveItem', 
               'Get-MgShareDriveItemContent', 'Get-MgShareItem', 
               'Get-MgShareItemContent', 'Get-MgShareItemCount', 
               'Get-MgShareItemLastModifiedByUser', 
               'Get-MgShareItemLastModifiedByUserMailboxSetting', 
               'Get-MgShareLastModifiedByUser', 
               'Get-MgShareLastModifiedByUserMailboxSetting', 'Get-MgShareList', 
               'Get-MgShareListColumn', 'Get-MgShareListColumnCount', 
               'Get-MgShareListColumnSourceColumn', 'Get-MgShareListContentType', 
               'Get-MgShareListContentTypeColumn', 
               'Get-MgShareListContentTypeColumnCount', 
               'Get-MgShareListContentTypeColumnLink', 
               'Get-MgShareListContentTypeColumnLinkCount', 
               'Get-MgShareListContentTypeColumnPosition', 
               'Get-MgShareListContentTypeColumnPositionCount', 
               'Get-MgShareListContentTypeColumnSourceColumn', 
               'Get-MgShareListContentTypeCompatibleHubContentType', 
               'Get-MgShareListContentTypeCount', 'Get-MgShareListCreatedByUser', 
               'Get-MgShareListCreatedByUserMailboxSetting', 
               'Get-MgShareListDrive', 'Get-MgShareListItem', 
               'Get-MgShareListItemActivityByInterval', 
               'Get-MgShareListItemAnalytic', 'Get-MgShareListItemCreatedByUser', 
               'Get-MgShareListItemCreatedByUserMailboxSetting', 
               'Get-MgShareListItemDocumentSetVersion', 
               'Get-MgShareListItemDocumentSetVersionCount', 
               'Get-MgShareListItemDocumentSetVersionField', 
               'Get-MgShareListItemDriveItem', 
               'Get-MgShareListItemDriveItemContent', 'Get-MgShareListItemField', 
               'Get-MgShareListItemVersion', 'Get-MgShareListItemVersionCount', 
               'Get-MgShareListItemVersionField', 'Get-MgShareListOperation', 
               'Get-MgShareListOperationCount', 'Get-MgShareListSubscription', 
               'Get-MgShareListSubscriptionCount', 'Get-MgSharePermission', 
               'Get-MgShareRoot', 'Get-MgShareRootContent', 
               'Get-MgShareSharedDriveItemSharedDriveItem', 'Get-MgShareSite', 
               'Get-MgUserDefaultDrive', 'Get-MgUserDrive', 'Get-MgUserDriveBundle', 
               'Get-MgUserDriveBundleContent', 'Get-MgUserDriveBundleCount', 
               'Get-MgUserDriveContentTypeBase', 
               'Get-MgUserDriveContentTypeBaseType', 
               'Get-MgUserDriveContentTypeBaseTypeCount', 'Get-MgUserDriveCount', 
               'Get-MgUserDriveCreatedByUser', 
               'Get-MgUserDriveCreatedByUserMailboxSetting', 
               'Get-MgUserDriveFollowing', 'Get-MgUserDriveFollowingContent', 
               'Get-MgUserDriveFollowingCount', 'Get-MgUserDriveItem', 
               'Get-MgUserDriveItemAnalytic', 
               'Get-MgUserDriveItemAnalyticItemActivityStat', 
               'Get-MgUserDriveItemAnalyticItemActivityStatActivity', 
               'Get-MgUserDriveItemAnalyticItemActivityStatCount', 
               'Get-MgUserDriveItemAnalyticLastSevenDay', 
               'Get-MgUserDriveItemAnalyticTime', 'Get-MgUserDriveItemChild', 
               'Get-MgUserDriveItemChildContent', 'Get-MgUserDriveItemChildCount', 
               'Get-MgUserDriveItemContent', 'Get-MgUserDriveItemCount', 
               'Get-MgUserDriveItemCreatedByUser', 
               'Get-MgUserDriveItemCreatedByUserMailboxSetting', 
               'Get-MgUserDriveItemItemLastModifiedByUser', 
               'Get-MgUserDriveItemItemLastModifiedByUserMailboxSetting', 
               'Get-MgUserDriveItemLastModifiedByUser', 
               'Get-MgUserDriveItemLastModifiedByUserMailboxSetting', 
               'Get-MgUserDriveItemListItem', 
               'Get-MgUserDriveItemListItemAnalytic', 
               'Get-MgUserDriveItemListItemCreatedByUser', 
               'Get-MgUserDriveItemListItemCreatedByUserMailboxSetting', 
               'Get-MgUserDriveItemListItemDocumentSetVersion', 
               'Get-MgUserDriveItemListItemDocumentSetVersionCount', 
               'Get-MgUserDriveItemListItemDocumentSetVersionField', 
               'Get-MgUserDriveItemListItemDriveItem', 
               'Get-MgUserDriveItemListItemDriveItemContent', 
               'Get-MgUserDriveItemListItemField', 
               'Get-MgUserDriveItemListItemVersion', 
               'Get-MgUserDriveItemListItemVersionCount', 
               'Get-MgUserDriveItemListItemVersionField', 
               'Get-MgUserDriveItemPermission', 
               'Get-MgUserDriveItemPermissionCount', 
               'Get-MgUserDriveItemSubscription', 
               'Get-MgUserDriveItemSubscriptionCount', 
               'Get-MgUserDriveItemThumbnail', 'Get-MgUserDriveItemThumbnailCount', 
               'Get-MgUserDriveItemVersion', 'Get-MgUserDriveItemVersionContent', 
               'Get-MgUserDriveItemVersionCount', 
               'Get-MgUserDriveLastModifiedByUser', 
               'Get-MgUserDriveLastModifiedByUserMailboxSetting', 
               'Get-MgUserDriveList', 'Get-MgUserDriveListColumn', 
               'Get-MgUserDriveListColumnCount', 
               'Get-MgUserDriveListColumnSourceColumn', 
               'Get-MgUserDriveListContentType', 
               'Get-MgUserDriveListContentTypeColumn', 
               'Get-MgUserDriveListContentTypeColumnCount', 
               'Get-MgUserDriveListContentTypeColumnLink', 
               'Get-MgUserDriveListContentTypeColumnLinkCount', 
               'Get-MgUserDriveListContentTypeColumnPosition', 
               'Get-MgUserDriveListContentTypeColumnPositionCount', 
               'Get-MgUserDriveListContentTypeColumnSourceColumn', 
               'Get-MgUserDriveListContentTypeCount', 
               'Get-MgUserDriveListCreatedByUser', 
               'Get-MgUserDriveListCreatedByUserMailboxSetting', 
               'Get-MgUserDriveListDrive', 'Get-MgUserDriveListItem', 
               'Get-MgUserDriveListItemAnalytic', 
               'Get-MgUserDriveListItemCreatedByUser', 
               'Get-MgUserDriveListItemCreatedByUserMailboxSetting', 
               'Get-MgUserDriveListItemDocumentSetVersion', 
               'Get-MgUserDriveListItemDocumentSetVersionCount', 
               'Get-MgUserDriveListItemDocumentSetVersionField', 
               'Get-MgUserDriveListItemDriveItem', 
               'Get-MgUserDriveListItemDriveItemContent', 
               'Get-MgUserDriveListItemField', 'Get-MgUserDriveListItemVersion', 
               'Get-MgUserDriveListItemVersionCount', 
               'Get-MgUserDriveListItemVersionField', 
               'Get-MgUserDriveListOperation', 'Get-MgUserDriveListOperationCount', 
               'Get-MgUserDriveListSubscription', 
               'Get-MgUserDriveListSubscriptionCount', 'Get-MgUserDriveRoot', 
               'Get-MgUserDriveRootAnalytic', 
               'Get-MgUserDriveRootAnalyticItemActivityStat', 
               'Get-MgUserDriveRootAnalyticItemActivityStatActivity', 
               'Get-MgUserDriveRootAnalyticItemActivityStatCount', 
               'Get-MgUserDriveRootAnalyticLastSevenDay', 
               'Get-MgUserDriveRootAnalyticTime', 'Get-MgUserDriveRootChild', 
               'Get-MgUserDriveRootChildContent', 'Get-MgUserDriveRootChildCount', 
               'Get-MgUserDriveRootContent', 'Get-MgUserDriveRootCreatedByUser', 
               'Get-MgUserDriveRootCreatedByUserMailboxSetting', 
               'Get-MgUserDriveRootItemLastModifiedByUser', 
               'Get-MgUserDriveRootItemLastModifiedByUserMailboxSetting', 
               'Get-MgUserDriveRootLastModifiedByUser', 
               'Get-MgUserDriveRootLastModifiedByUserMailboxSetting', 
               'Get-MgUserDriveRootListItem', 
               'Get-MgUserDriveRootListItemAnalytic', 
               'Get-MgUserDriveRootListItemCreatedByUser', 
               'Get-MgUserDriveRootListItemCreatedByUserMailboxSetting', 
               'Get-MgUserDriveRootListItemDocumentSetVersion', 
               'Get-MgUserDriveRootListItemDocumentSetVersionCount', 
               'Get-MgUserDriveRootListItemDocumentSetVersionField', 
               'Get-MgUserDriveRootListItemDriveItem', 
               'Get-MgUserDriveRootListItemDriveItemContent', 
               'Get-MgUserDriveRootListItemField', 
               'Get-MgUserDriveRootListItemVersion', 
               'Get-MgUserDriveRootListItemVersionCount', 
               'Get-MgUserDriveRootListItemVersionField', 
               'Get-MgUserDriveRootPermission', 
               'Get-MgUserDriveRootPermissionCount', 
               'Get-MgUserDriveRootSubscription', 
               'Get-MgUserDriveRootSubscriptionCount', 
               'Get-MgUserDriveRootThumbnail', 'Get-MgUserDriveRootThumbnailCount', 
               'Get-MgUserDriveRootVersion', 'Get-MgUserDriveRootVersionContent', 
               'Get-MgUserDriveRootVersionCount', 'Get-MgUserDriveSpecial', 
               'Get-MgUserDriveSpecialContent', 'Get-MgUserDriveSpecialCount', 
               'Grant-MgDriveItemPermission', 'Grant-MgDriveRootPermission', 
               'Grant-MgSharePermission', 'Invoke-MgCheckinDriveItem', 
               'Invoke-MgCheckinDriveRoot', 'Invoke-MgCheckoutDriveItem', 
               'Invoke-MgCheckoutDriveRoot', 
               'Invoke-MgExtractDriveItemSensitivityLabel', 
               'Invoke-MgExtractDriveRootSensitivityLabel', 
               'Invoke-MgFollowDriveItem', 'Invoke-MgFollowDriveRoot', 
               'Invoke-MgGraphDrive', 'Invoke-MgInviteDriveItem', 
               'Invoke-MgInviteDriveRoot', 'Invoke-MgPreviewDriveItem', 
               'Invoke-MgPreviewDriveRoot', 
               'Invoke-MgReauthorizeDriveItemSubscription', 
               'Invoke-MgReauthorizeDriveListSubscription', 
               'Invoke-MgReauthorizeDriveRootSubscription', 
               'Invoke-MgReauthorizeShareListSubscription', 'Invoke-MgRecentDrive', 
               'Invoke-MgUnfollowDriveItem', 'Invoke-MgUnfollowDriveRoot', 
               'Join-MgDriveListContentTypeWithHubSite', 
               'Join-MgShareListContentTypeWithHubSite', 'New-MgDrive', 
               'New-MgDriveBundle', 'New-MgDriveItem', 
               'New-MgDriveItemAnalyticItemActivityStat', 'New-MgDriveItemChild', 
               'New-MgDriveItemLink', 'New-MgDriveItemListItemDocumentSetVersion', 
               'New-MgDriveItemListItemVersion', 'New-MgDriveItemPermission', 
               'New-MgDriveItemSubscription', 'New-MgDriveItemThumbnail', 
               'New-MgDriveItemUploadSession', 'New-MgDriveItemVersion', 
               'New-MgDriveListColumn', 'New-MgDriveListContentType', 
               'New-MgDriveListContentTypeColumn', 
               'New-MgDriveListContentTypeColumnLink', 'New-MgDriveListItem', 
               'New-MgDriveListItemDocumentSetVersion', 
               'New-MgDriveListItemVersion', 'New-MgDriveListOperation', 
               'New-MgDriveListSubscription', 
               'New-MgDriveRootAnalyticItemActivityStat', 'New-MgDriveRootChild', 
               'New-MgDriveRootLink', 'New-MgDriveRootListItemDocumentSetVersion', 
               'New-MgDriveRootListItemVersion', 'New-MgDriveRootPermission', 
               'New-MgDriveRootSubscription', 'New-MgDriveRootThumbnail', 
               'New-MgDriveRootUploadSession', 'New-MgDriveRootVersion', 
               'New-MgGroupDrive', 'New-MgGroupDriveBundle', 'New-MgGroupDriveItem', 
               'New-MgGroupDriveItemAnalyticItemActivityStat', 
               'New-MgGroupDriveItemChild', 
               'New-MgGroupDriveItemListItemDocumentSetVersion', 
               'New-MgGroupDriveItemListItemVersion', 
               'New-MgGroupDriveItemPermission', 
               'New-MgGroupDriveItemSubscription', 'New-MgGroupDriveItemThumbnail', 
               'New-MgGroupDriveItemVersion', 'New-MgGroupDriveListColumn', 
               'New-MgGroupDriveListContentType', 
               'New-MgGroupDriveListContentTypeColumn', 
               'New-MgGroupDriveListContentTypeColumnLink', 
               'New-MgGroupDriveListItem', 
               'New-MgGroupDriveListItemDocumentSetVersion', 
               'New-MgGroupDriveListItemVersion', 'New-MgGroupDriveListOperation', 
               'New-MgGroupDriveListSubscription', 
               'New-MgGroupDriveRootAnalyticItemActivityStat', 
               'New-MgGroupDriveRootChild', 
               'New-MgGroupDriveRootListItemDocumentSetVersion', 
               'New-MgGroupDriveRootListItemVersion', 
               'New-MgGroupDriveRootPermission', 
               'New-MgGroupDriveRootSubscription', 'New-MgGroupDriveRootThumbnail', 
               'New-MgGroupDriveRootVersion', 'New-MgShareListColumn', 
               'New-MgShareListContentType', 'New-MgShareListContentTypeColumn', 
               'New-MgShareListContentTypeColumnLink', 'New-MgShareListItem', 
               'New-MgShareListItemDocumentSetVersion', 
               'New-MgShareListItemVersion', 'New-MgShareListOperation', 
               'New-MgShareListSubscription', 
               'New-MgShareSharedDriveItemSharedDriveItem', 'New-MgUserDrive', 
               'New-MgUserDriveBundle', 'New-MgUserDriveItem', 
               'New-MgUserDriveItemAnalyticItemActivityStat', 
               'New-MgUserDriveItemChild', 
               'New-MgUserDriveItemListItemDocumentSetVersion', 
               'New-MgUserDriveItemListItemVersion', 
               'New-MgUserDriveItemPermission', 'New-MgUserDriveItemSubscription', 
               'New-MgUserDriveItemThumbnail', 'New-MgUserDriveItemVersion', 
               'New-MgUserDriveListColumn', 'New-MgUserDriveListContentType', 
               'New-MgUserDriveListContentTypeColumn', 
               'New-MgUserDriveListContentTypeColumnLink', 
               'New-MgUserDriveListItem', 
               'New-MgUserDriveListItemDocumentSetVersion', 
               'New-MgUserDriveListItemVersion', 'New-MgUserDriveListOperation', 
               'New-MgUserDriveListSubscription', 
               'New-MgUserDriveRootAnalyticItemActivityStat', 
               'New-MgUserDriveRootChild', 
               'New-MgUserDriveRootListItemDocumentSetVersion', 
               'New-MgUserDriveRootListItemVersion', 
               'New-MgUserDriveRootPermission', 'New-MgUserDriveRootSubscription', 
               'New-MgUserDriveRootThumbnail', 'New-MgUserDriveRootVersion', 
               'Publish-MgDriveListContentType', 'Publish-MgShareListContentType', 
               'Remove-MgDrive', 'Remove-MgDriveItem', 'Remove-MgDriveItemAnalytic', 
               'Remove-MgDriveItemAnalyticItemActivityStat', 
               'Remove-MgDriveItemChild', 'Remove-MgDriveItemListItem', 
               'Remove-MgDriveItemListItemDocumentSetVersion', 
               'Remove-MgDriveItemListItemDocumentSetVersionField', 
               'Remove-MgDriveItemListItemField', 
               'Remove-MgDriveItemListItemVersion', 
               'Remove-MgDriveItemListItemVersionField', 
               'Remove-MgDriveItemPermanent', 'Remove-MgDriveItemPermission', 
               'Remove-MgDriveItemSubscription', 'Remove-MgDriveItemThumbnail', 
               'Remove-MgDriveItemVersion', 'Remove-MgDriveList', 
               'Remove-MgDriveListColumn', 'Remove-MgDriveListContentType', 
               'Remove-MgDriveListContentTypeColumn', 
               'Remove-MgDriveListContentTypeColumnLink', 'Remove-MgDriveListItem', 
               'Remove-MgDriveListItemDocumentSetVersion', 
               'Remove-MgDriveListItemDocumentSetVersionField', 
               'Remove-MgDriveListItemField', 'Remove-MgDriveListItemVersion', 
               'Remove-MgDriveListItemVersionField', 'Remove-MgDriveListOperation', 
               'Remove-MgDriveListSubscription', 'Remove-MgDriveRoot', 
               'Remove-MgDriveRootAnalytic', 
               'Remove-MgDriveRootAnalyticItemActivityStat', 
               'Remove-MgDriveRootChild', 'Remove-MgDriveRootListItem', 
               'Remove-MgDriveRootListItemDocumentSetVersion', 
               'Remove-MgDriveRootListItemDocumentSetVersionField', 
               'Remove-MgDriveRootListItemField', 
               'Remove-MgDriveRootListItemVersion', 
               'Remove-MgDriveRootListItemVersionField', 
               'Remove-MgDriveRootPermanent', 'Remove-MgDriveRootPermission', 
               'Remove-MgDriveRootSubscription', 'Remove-MgDriveRootThumbnail', 
               'Remove-MgDriveRootVersion', 'Remove-MgGroupDrive', 
               'Remove-MgGroupDriveItem', 'Remove-MgGroupDriveItemAnalytic', 
               'Remove-MgGroupDriveItemAnalyticItemActivityStat', 
               'Remove-MgGroupDriveItemChild', 'Remove-MgGroupDriveItemListItem', 
               'Remove-MgGroupDriveItemListItemDocumentSetVersion', 
               'Remove-MgGroupDriveItemListItemDocumentSetVersionField', 
               'Remove-MgGroupDriveItemListItemField', 
               'Remove-MgGroupDriveItemListItemVersion', 
               'Remove-MgGroupDriveItemListItemVersionField', 
               'Remove-MgGroupDriveItemPermission', 
               'Remove-MgGroupDriveItemSubscription', 
               'Remove-MgGroupDriveItemThumbnail', 
               'Remove-MgGroupDriveItemVersion', 'Remove-MgGroupDriveList', 
               'Remove-MgGroupDriveListColumn', 
               'Remove-MgGroupDriveListContentType', 
               'Remove-MgGroupDriveListContentTypeColumn', 
               'Remove-MgGroupDriveListContentTypeColumnLink', 
               'Remove-MgGroupDriveListItem', 
               'Remove-MgGroupDriveListItemDocumentSetVersion', 
               'Remove-MgGroupDriveListItemDocumentSetVersionField', 
               'Remove-MgGroupDriveListItemField', 
               'Remove-MgGroupDriveListItemVersion', 
               'Remove-MgGroupDriveListItemVersionField', 
               'Remove-MgGroupDriveListOperation', 
               'Remove-MgGroupDriveListSubscription', 'Remove-MgGroupDriveRoot', 
               'Remove-MgGroupDriveRootAnalytic', 
               'Remove-MgGroupDriveRootAnalyticItemActivityStat', 
               'Remove-MgGroupDriveRootChild', 'Remove-MgGroupDriveRootListItem', 
               'Remove-MgGroupDriveRootListItemDocumentSetVersion', 
               'Remove-MgGroupDriveRootListItemDocumentSetVersionField', 
               'Remove-MgGroupDriveRootListItemField', 
               'Remove-MgGroupDriveRootListItemVersion', 
               'Remove-MgGroupDriveRootListItemVersionField', 
               'Remove-MgGroupDriveRootPermission', 
               'Remove-MgGroupDriveRootSubscription', 
               'Remove-MgGroupDriveRootThumbnail', 
               'Remove-MgGroupDriveRootVersion', 'Remove-MgShareList', 
               'Remove-MgShareListColumn', 'Remove-MgShareListContentType', 
               'Remove-MgShareListContentTypeColumn', 
               'Remove-MgShareListContentTypeColumnLink', 'Remove-MgShareListItem', 
               'Remove-MgShareListItemDocumentSetVersion', 
               'Remove-MgShareListItemDocumentSetVersionField', 
               'Remove-MgShareListItemField', 'Remove-MgShareListItemVersion', 
               'Remove-MgShareListItemVersionField', 'Remove-MgShareListOperation', 
               'Remove-MgShareListSubscription', 'Remove-MgSharePermission', 
               'Remove-MgShareSharedDriveItemSharedDriveItem', 
               'Remove-MgUserDrive', 'Remove-MgUserDriveItem', 
               'Remove-MgUserDriveItemAnalytic', 
               'Remove-MgUserDriveItemAnalyticItemActivityStat', 
               'Remove-MgUserDriveItemChild', 'Remove-MgUserDriveItemListItem', 
               'Remove-MgUserDriveItemListItemDocumentSetVersion', 
               'Remove-MgUserDriveItemListItemDocumentSetVersionField', 
               'Remove-MgUserDriveItemListItemField', 
               'Remove-MgUserDriveItemListItemVersion', 
               'Remove-MgUserDriveItemListItemVersionField', 
               'Remove-MgUserDriveItemPermission', 
               'Remove-MgUserDriveItemSubscription', 
               'Remove-MgUserDriveItemThumbnail', 'Remove-MgUserDriveItemVersion', 
               'Remove-MgUserDriveList', 'Remove-MgUserDriveListColumn', 
               'Remove-MgUserDriveListContentType', 
               'Remove-MgUserDriveListContentTypeColumn', 
               'Remove-MgUserDriveListContentTypeColumnLink', 
               'Remove-MgUserDriveListItem', 
               'Remove-MgUserDriveListItemDocumentSetVersion', 
               'Remove-MgUserDriveListItemDocumentSetVersionField', 
               'Remove-MgUserDriveListItemField', 
               'Remove-MgUserDriveListItemVersion', 
               'Remove-MgUserDriveListItemVersionField', 
               'Remove-MgUserDriveListOperation', 
               'Remove-MgUserDriveListSubscription', 'Remove-MgUserDriveRoot', 
               'Remove-MgUserDriveRootAnalytic', 
               'Remove-MgUserDriveRootAnalyticItemActivityStat', 
               'Remove-MgUserDriveRootChild', 'Remove-MgUserDriveRootListItem', 
               'Remove-MgUserDriveRootListItemDocumentSetVersion', 
               'Remove-MgUserDriveRootListItemDocumentSetVersionField', 
               'Remove-MgUserDriveRootListItemField', 
               'Remove-MgUserDriveRootListItemVersion', 
               'Remove-MgUserDriveRootListItemVersionField', 
               'Remove-MgUserDriveRootPermission', 
               'Remove-MgUserDriveRootSubscription', 
               'Remove-MgUserDriveRootThumbnail', 'Remove-MgUserDriveRootVersion', 
               'Restore-MgDriveItem', 
               'Restore-MgDriveItemListItemDocumentSetVersion', 
               'Restore-MgDriveItemListItemVersion', 'Restore-MgDriveItemVersion', 
               'Restore-MgDriveListItemDocumentSetVersion', 
               'Restore-MgDriveListItemVersion', 'Restore-MgDriveRoot', 
               'Restore-MgDriveRootListItemDocumentSetVersion', 
               'Restore-MgDriveRootListItemVersion', 'Restore-MgDriveRootVersion', 
               'Restore-MgShareListItemDocumentSetVersion', 
               'Restore-MgShareListItemVersion', 'Search-MgDrive', 
               'Search-MgDriveItem', 'Search-MgDriveRoot', 
               'Set-MgDriveBundleContent', 'Set-MgDriveFollowingContent', 
               'Set-MgDriveItemChildContent', 'Set-MgDriveItemContent', 
               'Set-MgDriveItemListItemDriveItemContent', 
               'Set-MgDriveItemSensitivityLabel', 'Set-MgDriveItemVersionContent', 
               'Set-MgDriveListItemDriveItemContent', 
               'Set-MgDriveRootChildContent', 'Set-MgDriveRootContent', 
               'Set-MgDriveRootListItemDriveItemContent', 
               'Set-MgDriveRootSensitivityLabel', 'Set-MgDriveRootVersionContent', 
               'Set-MgDriveSpecialContent', 'Set-MgGroupDriveBundleContent', 
               'Set-MgGroupDriveFollowingContent', 
               'Set-MgGroupDriveItemChildContent', 'Set-MgGroupDriveItemContent', 
               'Set-MgGroupDriveItemListItemDriveItemContent', 
               'Set-MgGroupDriveItemVersionContent', 
               'Set-MgGroupDriveListItemDriveItemContent', 
               'Set-MgGroupDriveRootChildContent', 'Set-MgGroupDriveRootContent', 
               'Set-MgGroupDriveRootListItemDriveItemContent', 
               'Set-MgGroupDriveRootVersionContent', 
               'Set-MgGroupDriveSpecialContent', 'Set-MgShareDriveItemContent', 
               'Set-MgShareItemContent', 'Set-MgShareListItemDriveItemContent', 
               'Set-MgShareRootContent', 'Set-MgUserDriveBundleContent', 
               'Set-MgUserDriveFollowingContent', 
               'Set-MgUserDriveItemChildContent', 'Set-MgUserDriveItemContent', 
               'Set-MgUserDriveItemListItemDriveItemContent', 
               'Set-MgUserDriveItemVersionContent', 
               'Set-MgUserDriveListItemDriveItemContent', 
               'Set-MgUserDriveRootChildContent', 'Set-MgUserDriveRootContent', 
               'Set-MgUserDriveRootListItemDriveItemContent', 
               'Set-MgUserDriveRootVersionContent', 
               'Set-MgUserDriveSpecialContent', 'Test-MgDriveItemPermission', 
               'Test-MgDriveListContentTypePublished', 
               'Test-MgDriveRootPermission', 
               'Test-MgShareListContentTypePublished', 
               'Unpublish-MgDriveListContentType', 
               'Unpublish-MgShareListContentType', 'Update-MgDrive', 
               'Update-MgDriveCreatedByUserMailboxSetting', 'Update-MgDriveItem', 
               'Update-MgDriveItemAnalytic', 
               'Update-MgDriveItemAnalyticItemActivityStat', 
               'Update-MgDriveItemCreatedByUserMailboxSetting', 
               'Update-MgDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgDriveItemListItem', 
               'Update-MgDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgDriveItemListItemDocumentSetVersion', 
               'Update-MgDriveItemListItemDocumentSetVersionField', 
               'Update-MgDriveItemListItemField', 
               'Update-MgDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgDriveItemListItemVersion', 
               'Update-MgDriveItemListItemVersionField', 
               'Update-MgDriveItemPermission', 'Update-MgDriveItemSubscription', 
               'Update-MgDriveItemThumbnail', 'Update-MgDriveItemVersion', 
               'Update-MgDriveLastModifiedByUserMailboxSetting', 
               'Update-MgDriveList', 'Update-MgDriveListColumn', 
               'Update-MgDriveListContentType', 
               'Update-MgDriveListContentTypeColumn', 
               'Update-MgDriveListContentTypeColumnLink', 
               'Update-MgDriveListCreatedByUserMailboxSetting', 
               'Update-MgDriveListItem', 
               'Update-MgDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgDriveListItemDocumentSetVersion', 
               'Update-MgDriveListItemDocumentSetVersionField', 
               'Update-MgDriveListItemField', 
               'Update-MgDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgDriveListItemVersion', 
               'Update-MgDriveListItemVersionField', 
               'Update-MgDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgDriveListOperation', 'Update-MgDriveListSubscription', 
               'Update-MgDriveRoot', 'Update-MgDriveRootAnalytic', 
               'Update-MgDriveRootAnalyticItemActivityStat', 
               'Update-MgDriveRootCreatedByUserMailboxSetting', 
               'Update-MgDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgDriveRootListItem', 
               'Update-MgDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgDriveRootListItemDocumentSetVersion', 
               'Update-MgDriveRootListItemDocumentSetVersionField', 
               'Update-MgDriveRootListItemField', 
               'Update-MgDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgDriveRootListItemVersion', 
               'Update-MgDriveRootListItemVersionField', 
               'Update-MgDriveRootPermission', 'Update-MgDriveRootSubscription', 
               'Update-MgDriveRootThumbnail', 'Update-MgDriveRootVersion', 
               'Update-MgGroupDrive', 
               'Update-MgGroupDriveCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveItem', 'Update-MgGroupDriveItemAnalytic', 
               'Update-MgGroupDriveItemAnalyticItemActivityStat', 
               'Update-MgGroupDriveItemCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveItemListItem', 
               'Update-MgGroupDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveItemListItemDocumentSetVersion', 
               'Update-MgGroupDriveItemListItemDocumentSetVersionField', 
               'Update-MgGroupDriveItemListItemField', 
               'Update-MgGroupDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveItemListItemVersion', 
               'Update-MgGroupDriveItemListItemVersionField', 
               'Update-MgGroupDriveItemPermission', 
               'Update-MgGroupDriveItemSubscription', 
               'Update-MgGroupDriveItemThumbnail', 
               'Update-MgGroupDriveItemVersion', 
               'Update-MgGroupDriveLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveList', 'Update-MgGroupDriveListColumn', 
               'Update-MgGroupDriveListContentType', 
               'Update-MgGroupDriveListContentTypeColumn', 
               'Update-MgGroupDriveListContentTypeColumnLink', 
               'Update-MgGroupDriveListCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveListItem', 
               'Update-MgGroupDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveListItemDocumentSetVersion', 
               'Update-MgGroupDriveListItemDocumentSetVersionField', 
               'Update-MgGroupDriveListItemField', 
               'Update-MgGroupDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveListItemVersion', 
               'Update-MgGroupDriveListItemVersionField', 
               'Update-MgGroupDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveListOperation', 
               'Update-MgGroupDriveListSubscription', 'Update-MgGroupDriveRoot', 
               'Update-MgGroupDriveRootAnalytic', 
               'Update-MgGroupDriveRootAnalyticItemActivityStat', 
               'Update-MgGroupDriveRootCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveRootListItem', 
               'Update-MgGroupDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgGroupDriveRootListItemDocumentSetVersion', 
               'Update-MgGroupDriveRootListItemDocumentSetVersionField', 
               'Update-MgGroupDriveRootListItemField', 
               'Update-MgGroupDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgGroupDriveRootListItemVersion', 
               'Update-MgGroupDriveRootListItemVersionField', 
               'Update-MgGroupDriveRootPermission', 
               'Update-MgGroupDriveRootSubscription', 
               'Update-MgGroupDriveRootThumbnail', 
               'Update-MgGroupDriveRootVersion', 
               'Update-MgShareCreatedByUserMailboxSetting', 
               'Update-MgShareLastModifiedByUserMailboxSetting', 
               'Update-MgShareList', 'Update-MgShareListColumn', 
               'Update-MgShareListContentType', 
               'Update-MgShareListContentTypeColumn', 
               'Update-MgShareListContentTypeColumnLink', 
               'Update-MgShareListCreatedByUserMailboxSetting', 
               'Update-MgShareListItem', 
               'Update-MgShareListItemCreatedByUserMailboxSetting', 
               'Update-MgShareListItemDocumentSetVersion', 
               'Update-MgShareListItemDocumentSetVersionField', 
               'Update-MgShareListItemField', 
               'Update-MgShareListItemLastModifiedByUserMailboxSetting', 
               'Update-MgShareListItemVersion', 
               'Update-MgShareListItemVersionField', 
               'Update-MgShareListLastModifiedByUserMailboxSetting', 
               'Update-MgShareListOperation', 'Update-MgShareListSubscription', 
               'Update-MgSharePermission', 
               'Update-MgShareSharedDriveItemSharedDriveItem', 
               'Update-MgUserDrive', 
               'Update-MgUserDriveCreatedByUserMailboxSetting', 
               'Update-MgUserDriveItem', 'Update-MgUserDriveItemAnalytic', 
               'Update-MgUserDriveItemAnalyticItemActivityStat', 
               'Update-MgUserDriveItemCreatedByUserMailboxSetting', 
               'Update-MgUserDriveItemLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveItemListItem', 
               'Update-MgUserDriveItemListItemCreatedByUserMailboxSetting', 
               'Update-MgUserDriveItemListItemDocumentSetVersion', 
               'Update-MgUserDriveItemListItemDocumentSetVersionField', 
               'Update-MgUserDriveItemListItemField', 
               'Update-MgUserDriveItemListItemLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveItemListItemVersion', 
               'Update-MgUserDriveItemListItemVersionField', 
               'Update-MgUserDriveItemPermission', 
               'Update-MgUserDriveItemSubscription', 
               'Update-MgUserDriveItemThumbnail', 'Update-MgUserDriveItemVersion', 
               'Update-MgUserDriveLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveList', 'Update-MgUserDriveListColumn', 
               'Update-MgUserDriveListContentType', 
               'Update-MgUserDriveListContentTypeColumn', 
               'Update-MgUserDriveListContentTypeColumnLink', 
               'Update-MgUserDriveListCreatedByUserMailboxSetting', 
               'Update-MgUserDriveListItem', 
               'Update-MgUserDriveListItemCreatedByUserMailboxSetting', 
               'Update-MgUserDriveListItemDocumentSetVersion', 
               'Update-MgUserDriveListItemDocumentSetVersionField', 
               'Update-MgUserDriveListItemField', 
               'Update-MgUserDriveListItemLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveListItemVersion', 
               'Update-MgUserDriveListItemVersionField', 
               'Update-MgUserDriveListLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveListOperation', 
               'Update-MgUserDriveListSubscription', 'Update-MgUserDriveRoot', 
               'Update-MgUserDriveRootAnalytic', 
               'Update-MgUserDriveRootAnalyticItemActivityStat', 
               'Update-MgUserDriveRootCreatedByUserMailboxSetting', 
               'Update-MgUserDriveRootLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveRootListItem', 
               'Update-MgUserDriveRootListItemCreatedByUserMailboxSetting', 
               'Update-MgUserDriveRootListItemDocumentSetVersion', 
               'Update-MgUserDriveRootListItemDocumentSetVersionField', 
               'Update-MgUserDriveRootListItemField', 
               'Update-MgUserDriveRootListItemLastModifiedByUserMailboxSetting', 
               'Update-MgUserDriveRootListItemVersion', 
               'Update-MgUserDriveRootListItemVersionField', 
               'Update-MgUserDriveRootPermission', 
               'Update-MgUserDriveRootSubscription', 
               'Update-MgUserDriveRootThumbnail', 'Update-MgUserDriveRootVersion'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInvwYJKoZIhvcNAQcCoIInsDCCJ6wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBE+uaThc5lNh7Q
# uF+kWUTRzfkgom0MwJntO9alM8aMqqCCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIKdG27rWqWioltdyZp7MttKe
# OlRfCwWdC0Evd5NYxIcvMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAHIm2EOPVelI2yzgF4Iq4tjEr3zM3xutiswes30rQcrFtlut9l6L8C9k9
# ZFG2fdjYlA2Gy3uPWi3ZUQ9hD0oUmAVaHKzvyJkk3m1ldh4ZPIR194Nz1fStu5Rc
# fbQ/i0HTQ3l7PDXivf2jW5V55Td9qGF2a6k+S3bnjqtTut0abPEy0JAnjlkQARaA
# PI96tEjR6Y0X2IE1IlZAlXQuNxqtkK0Toy7rKbZw/eZ3Q6qcrHE8CSveGZm3BCe1
# ciLGHCpfXUQWXUIWCrhJsjNRwFUFhgG2WtMqx9jRLMs4dc/7Udkt3JHIFvJi4Eku
# /26n6r0gwuOAD1GjU8rgwsQpAQ7QdqGCFykwghclBgorBgEEAYI3AwMBMYIXFTCC
# FxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCB1g7xXCAhyf7+XwZyGJ0+b2LtRfSWecmLvbtX8mtWq+QIGZLg+iRyP
# GBMyMDIzMDcyNjE5MTkwMy42MTJaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OkZDNDEtNEJENC1EMjIwMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAG59gANZVRPvAMAAQAAAbkwDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjIw
# OTIwMjAyMjE3WhcNMjMxMjE0MjAyMjE3WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpGQzQxLTRC
# RDQtRDIyMDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAONJPslh9RbHyQECbUIINxMF
# 5uQkyN07VIShITXubLpWnANgBCLvCcJl7o/2HHORnsRcmSINJ/qclAmLIrOjnYnr
# bocAnixiMEXC+a1sZ84qxYWtEVY7VYw0LCczY+86U/8shgxqsaezKpWriPOcpV1S
# h8SsOxf30yO7jvld/IBA3T6lHM2pT/HRjWk/r9uyx0Q4atx0mkLVYS9y55/oTlKL
# E00h792S+maadAdy3VgTweiwoEOXD785wv3h+fwH/wTQtC9lhAxhMO4p+OP9888W
# xkbl6BqRWXud54RTzqp2Vr+yen1Q1A6umyMB7Xq0snIYG5B1Acc4UgJlPQ/ZiMkq
# gxQNFCWQvz0G9oLgSPD8Ky0AkX22PcDOboPuNT4RceWPX0UVZUsX9IUgs7QF41Hi
# QSwEeOOHGyrfQdmSslATrbmH/18M5QrsTM5JINjct9G42xqN8VF9Z8WOiGMjNbvl
# pcEmmysYl5QyhrEDoFnQTU7bFrD3JX0fIfu1sbLWeBqXwbp4Z8yACTtphK2VbzOv
# i4vc0RCmRNzvYQQ2PjZ7NaTXE4Gu3vggAJ+rtzUTAfJotvOSqcMgNwLZa1Y+ET/l
# b0VyjrYwFuHtg0QWyQjP5350LTpv086pyVUh4A3w/Os5hTGFZgFe5bCyMnpY09M0
# yPdHaQ/56oYUsSIcyKyVAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUt7A4cdtYQ5oJ
# jE1ZqrSonp41RFIwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAM3cZ7NFUHRMsLKz
# jl7rJPIkv7oJ+s9kkut0hZif9WSt60SzYGULp1zmdPqc+w8eHTkhqX0GKCp2TTqS
# zBXBhwHOm8+p6hUxNlDewGMZUos952aTXblAT3OKBnfVBLQyUavrSjuJGZAW30cN
# Y3rjVDUlGD+VygQHySaDaviJQbK6/6fQvUUFoqIk3ldGfjnAtnebsVlqh6WWamVc
# 5AZdpWR1jSzN/oxKYqc1BG4SxxlPtcfrAdBz/cU4bxVXqAAf02NZscvJNpRnOALf
# 5kVo2HupJXCsk9TzP5PNW2sTS3TmwhIQmPxr0E0UqOojUrBJUOhbITAxcnSa/IMl
# uL1HXRtLQZI+xs2eRtuPOUsKUW71/1YeqsYCLHLvu82ceDVQQvP7GHEEkp2kEjio
# fbjYErBo2iCEaxxeX4Z9HvAgA4MsQkbn6e4EFQf13sP+Kn3XgMIvJbqLJeFcQja+
# SUeOXu5cfkxe0GzTNojdyIwzaHlhOflVRZNrxee3B+yZwd3JHDIvv71uSI/SIzzt
# 9cU2GyHQVqxBSrRtKW6W8Vw7zpVvoVsIv3ljxg+7NiGSlXX1s7zbBNDMUj9OnzOl
# HK/3mrOU8YEuRf6RwakW5UCeGamy5MiKu2YuyKiGBCv4OGhPstNe7ALkEOh8BX12
# t4ntuYu+gw9L6yCPY0jWYaQtzAP9MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpG
# QzQxLTRCRDQtRDIyMDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAx2IeGHhk58MQkzzSWknGcLjfgTqggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOhrThYwIhgPMjAyMzA3MjYxNTQ3MzRaGA8yMDIzMDcyNzE1NDczNFowdDA6Bgor
# BgEEAYRZCgQBMSwwKjAKAgUA6GtOFgIBADAHAgEAAgJbCDAHAgEAAgISSTAKAgUA
# 6GyflgIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAID
# B6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBAI2Es52+ysrlzPRZyjxu
# zmh+s96B3/hEUbN/Qe9jG9pUx5F3KUme1rXA4R3KxEFXA/u0qDKeV63l7YyuEKhm
# iAMYK0F2qYwi05DNVTpvTPNErwY186W+xYt22NzTV03FUa0Bos6cKTscSoYmvJtM
# J3yLB3S8CTPaHeDLeTYdmqinMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAG59gANZVRPvAMAAQAAAbkwDQYJYIZIAWUDBAIB
# BQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQgmAfmpkydQRl7DFE+HUEvU9+6ltaQhpUUHuTJJv3/p+AwgfoGCyqGSIb3DQEJ
# EAIvMYHqMIHnMIHkMIG9BCBk60bO8W85uTAfJVEO3vX2aLaQFcgcGpdwsOoi+foP
# 9DCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABufYA
# DWVUT7wDAAEAAAG5MCIEIA7OI0zSWyqhS74R8aeBsjSUVl0pIjw4xYSyVkwfm9Zp
# MA0GCSqGSIb3DQEBCwUABIICABrxZAgyarGcqcsMH98B1Ca8temTackh4YZXn2me
# GMTlWOX7bAqBd2tVCXZqdsq5jZq/TeKMCJetJgFaLJK8vFw7dIAS1fVhVx9NutGJ
# mUP/XuPFA1fCxNcjGCP/h4UJRFghplKvAxx+DXefL22UqTzEab3xqYS76fgfdENV
# iNOfWBDd4KFrkJJfXySV44uQ8rHP51o0mLuhauT8qjcrAfKndl1+LO04AGZ9NNMc
# UnlqH0TrVxvT4FldxEOebsp58JIAadkIY+W6+7DwZ2MLaM5MKWeSxqlAtkTyJbFJ
# J++jJB4y0AmGT6H2S1Fifne2CTZRxEyxbsx/WiwTgoxCF9UKVCjHX5cemPSndokY
# ZE5ymUJX3bhB+Z4RzdKorWj0wISC7X+8//yqu1zKx6dKRaHlEd83PYHKsBkYgVzV
# 7Z5UrLQtmh1s0LpctvpIHudRLDjQnpQkqA/O+cDU2xLGBsdtKkMQ0GolauFooBco
# Oa0F4puEL/9SxK0IZ92ewo89VUoDU05MNGgx+l3gEZIUnB8NZUloidL2X3abZXt9
# yBhGfVgAG3oFFXN0EQ2fcnFYbbsvKpvuZNGaNAezfYd1bvDjWevNkHqXsQRxGpRE
# Uva651Hs2ScZDjnHwYYR8acraBZQzwcSyaotVarsRFzKoknAVTQip8N1MVJA/xcN
# 1jgY
# SIG # End signature block
