#
# Module manifest for module 'Microsoft.Graph.Beta.Devices.CorporateManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/26/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Devices.CorporateManagement.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'ebbf4df4-1be0-458b-a73c-6204060e5c3e'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.2.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 
               './bin/Microsoft.Graph.Beta.Devices.CorporateManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 
               './Microsoft.Graph.Beta.Devices.CorporateManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 
               'Clear-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistration', 
               'Get-MgBetaDeviceAppManagement', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtection', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppManagementDefaultManagedAppProtection', 
               'Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppManagementEnterpriseCodeSigningCertificate', 
               'Get-MgBetaDeviceAppManagementEnterpriseCodeSigningCertificateCount', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfiguration', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationAssignment', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationCount', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationDeviceStatusCount', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationGroupAssignmentCount', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationUserStatus', 
               'Get-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationUserStatusCount', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtection', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppManagementManagedAppPolicy', 
               'Get-MgBetaDeviceAppManagementManagedAppPolicyCount', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistration', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationCount', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationOperation', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationOperationCount', 
               'Get-MgBetaDeviceAppManagementManagedAppRegistrationUserIdWithFlaggedAppRegistration', 
               'Get-MgBetaDeviceAppManagementManagedAppStatus', 
               'Get-MgBetaDeviceAppManagementManagedAppStatusCount', 
               'Get-MgBetaDeviceAppManagementManagedEBook', 
               'Get-MgBetaDeviceAppManagementManagedEBookAssignment', 
               'Get-MgBetaDeviceAppManagementManagedEBookAssignmentCount', 
               'Get-MgBetaDeviceAppManagementManagedEBookCategory', 
               'Get-MgBetaDeviceAppManagementManagedEBookCategoryCount', 
               'Get-MgBetaDeviceAppManagementManagedEBookCount', 
               'Get-MgBetaDeviceAppManagementManagedEBookDeviceState', 
               'Get-MgBetaDeviceAppManagementManagedEBookDeviceStateCount', 
               'Get-MgBetaDeviceAppManagementManagedEBookInstallSummary', 
               'Get-MgBetaDeviceAppManagementManagedEBookUserStateSummary', 
               'Get-MgBetaDeviceAppManagementManagedEBookUserStateSummaryCount', 
               'Get-MgBetaDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Get-MgBetaDeviceAppManagementManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyCount', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgBetaDeviceAppManagementMobileApp', 
               'Get-MgBetaDeviceAppManagementMobileAppAsManagedMobileLobApp', 
               'Get-MgBetaDeviceAppManagementMobileAppAsMobileLobApp', 
               'Get-MgBetaDeviceAppManagementMobileAppAssignment', 
               'Get-MgBetaDeviceAppManagementMobileAppAssignmentCount', 
               'Get-MgBetaDeviceAppManagementMobileAppCategory', 
               'Get-MgBetaDeviceAppManagementMobileAppCategoryCount', 
               'Get-MgBetaDeviceAppManagementMobileAppConfiguration', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationAssignment', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationCount', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatusCount', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusCount', 
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Get-MgBetaDeviceAppManagementMobileAppCount', 
               'Get-MgBetaDeviceAppManagementMobileAppCountAsManagedMobileLobApp', 
               'Get-MgBetaDeviceAppManagementMobileAppCountAsMobileLobApp', 
               'Get-MgBetaDeviceAppManagementMobileAppRelationship', 
               'Get-MgBetaDeviceAppManagementMobileAppRelationshipCount', 
               'Get-MgBetaDeviceAppManagementPolicySet', 
               'Get-MgBetaDeviceAppManagementPolicySetAssignment', 
               'Get-MgBetaDeviceAppManagementPolicySetAssignmentCount', 
               'Get-MgBetaDeviceAppManagementPolicySetCount', 
               'Get-MgBetaDeviceAppManagementPolicySetItem', 
               'Get-MgBetaDeviceAppManagementPolicySetItemCount', 
               'Get-MgBetaDeviceAppManagementSymantecCodeSigningCertificate', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfiguration', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAppCount', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationCount', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSetting', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSettingCount', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSettingDefinition', 
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSettingDefinitionCount', 
               'Get-MgBetaDeviceAppManagementTask', 
               'Get-MgBetaDeviceAppManagementTaskCount', 
               'Get-MgBetaDeviceAppManagementVppToken', 
               'Get-MgBetaDeviceAppManagementVppTokenCount', 
               'Get-MgBetaDeviceAppManagementVppTokenLicenseForApp', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicy', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicyAssignment', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicyCount', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicyDeploySummary', 
               'Get-MgBetaDeviceAppManagementWdacSupplementalPolicyDeviceStatus', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistration', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistrationCount', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyCount', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionWipeAction', 
               'Get-MgBetaDeviceAppManagementWindowsInformationProtectionWipeActionCount', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtection', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppManagementWindowsManagementApp', 
               'Get-MgBetaUserDeviceEnrollmentConfiguration', 
               'Get-MgBetaUserDeviceEnrollmentConfigurationAssignment', 
               'Get-MgBetaUserDeviceEnrollmentConfigurationAssignmentCount', 
               'Get-MgBetaUserDeviceEnrollmentConfigurationCount', 
               'Get-MgBetaUserDeviceManagementTroubleshootingEvent', 
               'Get-MgBetaUserDeviceManagementTroubleshootingEventCount', 
               'Get-MgBetaUserManagedAppRegistration', 
               'Get-MgBetaUserManagedAppRegistrationCount', 
               'Get-MgBetaUserManagedDevice', 
               'Get-MgBetaUserManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Get-MgBetaUserManagedDeviceAssignmentFilterEvaluationStatusDetailCount', 
               'Get-MgBetaUserManagedDeviceCategory', 
               'Get-MgBetaUserManagedDeviceCompliancePolicyState', 
               'Get-MgBetaUserManagedDeviceCompliancePolicyStateCount', 
               'Get-MgBetaUserManagedDeviceConfigurationState', 
               'Get-MgBetaUserManagedDeviceConfigurationStateCount', 
               'Get-MgBetaUserManagedDeviceCount', 
               'Get-MgBetaUserManagedDeviceDetectedApp', 
               'Get-MgBetaUserManagedDeviceDetectedAppCount', 
               'Get-MgBetaUserManagedDeviceHealthScriptState', 
               'Get-MgBetaUserManagedDeviceHealthScriptStateCount', 
               'Get-MgBetaUserManagedDeviceLogCollectionRequestCount', 
               'Get-MgBetaUserManagedDeviceLogCollectionResponse', 
               'Get-MgBetaUserManagedDeviceMobileAppConfigurationState', 
               'Get-MgBetaUserManagedDeviceMobileAppConfigurationStateCount', 
               'Get-MgBetaUserManagedDeviceSecurityBaselineState', 
               'Get-MgBetaUserManagedDeviceSecurityBaselineStateCount', 
               'Get-MgBetaUserManagedDeviceSecurityBaselineStateSettingState', 
               'Get-MgBetaUserManagedDeviceSecurityBaselineStateSettingStateCount', 
               'Get-MgBetaUserManagedDeviceUser', 
               'Get-MgBetaUserManagedDeviceWindowsProtectionState', 
               'Get-MgBetaUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgBetaUserManagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Get-MgBetaUserMobileAppIntentAndState', 
               'Get-MgBetaUserMobileAppIntentAndStateCount', 
               'Get-MgBetaUserMobileAppTroubleshootingEvent', 
               'Get-MgBetaUserMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Get-MgBetaUserMobileAppTroubleshootingEventAppLogCollectionRequestCount', 
               'Get-MgBetaUserMobileAppTroubleshootingEventCount', 
               'Get-MgBetaUserWindowsInformationProtectionDeviceRegistration', 
               'Get-MgBetaUserWindowsInformationProtectionDeviceRegistrationCount', 
               'Invoke-MgBetaHasDeviceAppManagementAndroidManagedAppProtectionPayloadLink', 
               'Invoke-MgBetaHasDeviceAppManagementiOSLobAppProvisioningConfigurationPayloadLink', 
               'Invoke-MgBetaHasDeviceAppManagementiOSManagedAppProtectionPayloadLink', 
               'Invoke-MgBetaHasDeviceAppManagementMdmWindowsInformationProtectionPolicyPayloadLink', 
               'Invoke-MgBetaHasDeviceAppManagementMobileAppPayloadLink', 
               'Invoke-MgBetaHasDeviceAppManagementTargetedManagedAppConfigurationPayloadLink', 
               'Invoke-MgBetaTargetDeviceAppManagementManagedAppPolicyApp', 
               'Invoke-MgBetaTargetDeviceAppManagementManagedAppRegistrationAppliedPolicyApp', 
               'Invoke-MgBetaTargetDeviceAppManagementManagedAppRegistrationIntendedPolicyApp', 
               'Invoke-MgBetaTargetDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Invoke-MgBetaTargetDeviceAppManagementWindowsManagedAppProtectionApp', 
               'New-MgBetaDeviceAppManagementAndroidManagedAppProtection', 
               'New-MgBetaDeviceAppManagementAndroidManagedAppProtectionApp', 
               'New-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'New-MgBetaDeviceAppManagementDefaultManagedAppProtection', 
               'New-MgBetaDeviceAppManagementDefaultManagedAppProtectionApp', 
               'New-MgBetaDeviceAppManagementEnterpriseCodeSigningCertificate', 
               'New-MgBetaDeviceAppManagementiOSLobAppProvisioningConfiguration', 
               'New-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationAssignment', 
               'New-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationDeviceStatus', 
               'New-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationGroupAssignment', 
               'New-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationUserStatus', 
               'New-MgBetaDeviceAppManagementiOSManagedAppProtection', 
               'New-MgBetaDeviceAppManagementiOSManagedAppProtectionApp', 
               'New-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'New-MgBetaDeviceAppManagementManagedAppPolicy', 
               'New-MgBetaDeviceAppManagementManagedAppRegistration', 
               'New-MgBetaDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'New-MgBetaDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'New-MgBetaDeviceAppManagementManagedAppRegistrationOperation', 
               'New-MgBetaDeviceAppManagementManagedAppStatus', 
               'New-MgBetaDeviceAppManagementManagedEBook', 
               'New-MgBetaDeviceAppManagementManagedEBookAssignment', 
               'New-MgBetaDeviceAppManagementManagedEBookCategory', 
               'New-MgBetaDeviceAppManagementManagedEBookDeviceState', 
               'New-MgBetaDeviceAppManagementManagedEBookUserStateSummary', 
               'New-MgBetaDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'New-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'New-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'New-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgBetaDeviceAppManagementMobileApp', 
               'New-MgBetaDeviceAppManagementMobileAppAssignment', 
               'New-MgBetaDeviceAppManagementMobileAppCategory', 
               'New-MgBetaDeviceAppManagementMobileAppConfiguration', 
               'New-MgBetaDeviceAppManagementMobileAppConfigurationAssignment', 
               'New-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus', 
               'New-MgBetaDeviceAppManagementMobileAppRelationship', 
               'New-MgBetaDeviceAppManagementPolicySet', 
               'New-MgBetaDeviceAppManagementPolicySetAssignment', 
               'New-MgBetaDeviceAppManagementPolicySetItem', 
               'New-MgBetaDeviceAppManagementTargetedManagedAppConfiguration', 
               'New-MgBetaDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'New-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'New-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSetting', 
               'New-MgBetaDeviceAppManagementTask', 
               'New-MgBetaDeviceAppManagementVppToken', 
               'New-MgBetaDeviceAppManagementWdacSupplementalPolicy', 
               'New-MgBetaDeviceAppManagementWdacSupplementalPolicyAssignment', 
               'New-MgBetaDeviceAppManagementWdacSupplementalPolicyDeviceStatus', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistration', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionPolicy', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgBetaDeviceAppManagementWindowsInformationProtectionWipeAction', 
               'New-MgBetaDeviceAppManagementWindowsManagedAppProtection', 
               'New-MgBetaDeviceAppManagementWindowsManagedAppProtectionApp', 
               'New-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignment', 
               'New-MgBetaUserDeviceEnrollmentConfiguration', 
               'New-MgBetaUserDeviceEnrollmentConfigurationAssignment', 
               'New-MgBetaUserDeviceManagementTroubleshootingEvent', 
               'New-MgBetaUserManagedDevice', 
               'New-MgBetaUserManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'New-MgBetaUserManagedDeviceCompliancePolicyState', 
               'New-MgBetaUserManagedDeviceConfigurationState', 
               'New-MgBetaUserManagedDeviceHealthScriptState', 
               'New-MgBetaUserManagedDeviceLogCollectionResponse', 
               'New-MgBetaUserManagedDeviceMobileAppConfigurationState', 
               'New-MgBetaUserManagedDeviceSecurityBaselineState', 
               'New-MgBetaUserManagedDeviceSecurityBaselineStateSettingState', 
               'New-MgBetaUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'New-MgBetaUserMobileAppIntentAndState', 
               'New-MgBetaUserMobileAppTroubleshootingEvent', 
               'New-MgBetaUserMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Remove-MgBetaDeviceAppManagementAndroidManagedAppProtection', 
               'Remove-MgBetaDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Remove-MgBetaDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppManagementDefaultManagedAppProtection', 
               'Remove-MgBetaDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppManagementEnterpriseCodeSigningCertificate', 
               'Remove-MgBetaDeviceAppManagementiOSLobAppProvisioningConfiguration', 
               'Remove-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationAssignment', 
               'Remove-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Remove-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Remove-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationUserStatus', 
               'Remove-MgBetaDeviceAppManagementiOSManagedAppProtection', 
               'Remove-MgBetaDeviceAppManagementiOSManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Remove-MgBetaDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppManagementManagedAppPolicy', 
               'Remove-MgBetaDeviceAppManagementManagedAppRegistration', 
               'Remove-MgBetaDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Remove-MgBetaDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Remove-MgBetaDeviceAppManagementManagedAppRegistrationOperation', 
               'Remove-MgBetaDeviceAppManagementManagedAppStatus', 
               'Remove-MgBetaDeviceAppManagementManagedEBook', 
               'Remove-MgBetaDeviceAppManagementManagedEBookAssignment', 
               'Remove-MgBetaDeviceAppManagementManagedEBookCategory', 
               'Remove-MgBetaDeviceAppManagementManagedEBookDeviceState', 
               'Remove-MgBetaDeviceAppManagementManagedEBookInstallSummary', 
               'Remove-MgBetaDeviceAppManagementManagedEBookUserStateSummary', 
               'Remove-MgBetaDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Remove-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Remove-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgBetaDeviceAppManagementMobileApp', 
               'Remove-MgBetaDeviceAppManagementMobileAppAssignment', 
               'Remove-MgBetaDeviceAppManagementMobileAppCategory', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfiguration', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfigurationAssignment', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Remove-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Remove-MgBetaDeviceAppManagementMobileAppRelationship', 
               'Remove-MgBetaDeviceAppManagementPolicySet', 
               'Remove-MgBetaDeviceAppManagementPolicySetAssignment', 
               'Remove-MgBetaDeviceAppManagementPolicySetItem', 
               'Remove-MgBetaDeviceAppManagementSymantecCodeSigningCertificate', 
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfiguration', 
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSetting', 
               'Remove-MgBetaDeviceAppManagementTask', 
               'Remove-MgBetaDeviceAppManagementVppToken', 
               'Remove-MgBetaDeviceAppManagementWdacSupplementalPolicy', 
               'Remove-MgBetaDeviceAppManagementWdacSupplementalPolicyAssignment', 
               'Remove-MgBetaDeviceAppManagementWdacSupplementalPolicyDeploySummary', 
               'Remove-MgBetaDeviceAppManagementWdacSupplementalPolicyDeviceStatus', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistration', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgBetaDeviceAppManagementWindowsInformationProtectionWipeAction', 
               'Remove-MgBetaDeviceAppManagementWindowsManagedAppProtection', 
               'Remove-MgBetaDeviceAppManagementWindowsManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignment', 
               'Remove-MgBetaUserDeviceEnrollmentConfiguration', 
               'Remove-MgBetaUserDeviceEnrollmentConfigurationAssignment', 
               'Remove-MgBetaUserDeviceManagementTroubleshootingEvent', 
               'Remove-MgBetaUserManagedDevice', 
               'Remove-MgBetaUserManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Remove-MgBetaUserManagedDeviceCategory', 
               'Remove-MgBetaUserManagedDeviceCompliancePolicyState', 
               'Remove-MgBetaUserManagedDeviceConfigurationState', 
               'Remove-MgBetaUserManagedDeviceHealthScriptState', 
               'Remove-MgBetaUserManagedDeviceLogCollectionResponse', 
               'Remove-MgBetaUserManagedDeviceMobileAppConfigurationState', 
               'Remove-MgBetaUserManagedDeviceSecurityBaselineState', 
               'Remove-MgBetaUserManagedDeviceSecurityBaselineStateSettingState', 
               'Remove-MgBetaUserManagedDeviceWindowsProtectionState', 
               'Remove-MgBetaUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgBetaUserMobileAppIntentAndState', 
               'Remove-MgBetaUserMobileAppTroubleshootingEvent', 
               'Remove-MgBetaUserMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Rename-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSetting', 
               'Revoke-MgBetaDeviceAppManagementVppTokenLicense', 
               'Set-MgBetaDeviceAppManagementIosLobAppProvisioningConfiguration', 
               'Set-MgBetaDeviceAppManagementManagedEBook', 
               'Set-MgBetaDeviceAppManagementMobileApp', 
               'Set-MgBetaDeviceAppManagementMobileAppConfiguration', 
               'Set-MgBetaDeviceAppManagementTargetedManagedAppConfiguration', 
               'Set-MgBetaDeviceAppManagementWdacSupplementalPolicy', 
               'Set-MgBetaDeviceAppManagementWindowsManagedAppProtection', 
               'Sync-MgBetaDeviceAppManagementMicrosoftStoreForBusinessApp', 
               'Sync-MgBetaDeviceAppManagementVppTokenLicense', 
               'Sync-MgBetaDeviceAppManagementVppTokenLicenseCount', 
               'Test-MgBetaDeviceAppManagementMobileAppXml', 
               'Update-MgBetaDeviceAppManagement', 
               'Update-MgBetaDeviceAppManagementAndroidManagedAppProtection', 
               'Update-MgBetaDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Update-MgBetaDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppManagementDefaultManagedAppProtection', 
               'Update-MgBetaDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppManagementEnterpriseCodeSigningCertificate', 
               'Update-MgBetaDeviceAppManagementiOSLobAppProvisioningConfiguration', 
               'Update-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationAssignment', 
               'Update-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Update-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Update-MgBetaDeviceAppManagementiOSLobAppProvisioningConfigurationUserStatus', 
               'Update-MgBetaDeviceAppManagementiOSManagedAppProtection', 
               'Update-MgBetaDeviceAppManagementiOSManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Update-MgBetaDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppManagementManagedAppPolicy', 
               'Update-MgBetaDeviceAppManagementManagedAppRegistration', 
               'Update-MgBetaDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Update-MgBetaDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Update-MgBetaDeviceAppManagementManagedAppRegistrationOperation', 
               'Update-MgBetaDeviceAppManagementManagedAppStatus', 
               'Update-MgBetaDeviceAppManagementManagedEBook', 
               'Update-MgBetaDeviceAppManagementManagedEBookAssignment', 
               'Update-MgBetaDeviceAppManagementManagedEBookCategory', 
               'Update-MgBetaDeviceAppManagementManagedEBookDeviceState', 
               'Update-MgBetaDeviceAppManagementManagedEBookInstallSummary', 
               'Update-MgBetaDeviceAppManagementManagedEBookUserStateSummary', 
               'Update-MgBetaDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Update-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Update-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Update-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgBetaDeviceAppManagementMobileApp', 
               'Update-MgBetaDeviceAppManagementMobileAppAssignment', 
               'Update-MgBetaDeviceAppManagementMobileAppCategory', 
               'Update-MgBetaDeviceAppManagementMobileAppConfiguration', 
               'Update-MgBetaDeviceAppManagementMobileAppConfigurationAssignment', 
               'Update-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Update-MgBetaDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Update-MgBetaDeviceAppManagementMobileAppRelationship', 
               'Update-MgBetaDeviceAppManagementMultipleMobileAppRelationship', 
               'Update-MgBetaDeviceAppManagementMultiplePolicySet', 
               'Update-MgBetaDeviceAppManagementPolicySet', 
               'Update-MgBetaDeviceAppManagementPolicySetAssignment', 
               'Update-MgBetaDeviceAppManagementPolicySetItem', 
               'Update-MgBetaDeviceAppManagementSymantecCodeSigningCertificate', 
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration', 
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfigurationSetting', 
               'Update-MgBetaDeviceAppManagementTask', 
               'Update-MgBetaDeviceAppManagementTaskStatus', 
               'Update-MgBetaDeviceAppManagementVppToken', 
               'Update-MgBetaDeviceAppManagementWdacSupplementalPolicy', 
               'Update-MgBetaDeviceAppManagementWdacSupplementalPolicyAssignment', 
               'Update-MgBetaDeviceAppManagementWdacSupplementalPolicyDeploySummary', 
               'Update-MgBetaDeviceAppManagementWdacSupplementalPolicyDeviceStatus', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionDeviceRegistration', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgBetaDeviceAppManagementWindowsInformationProtectionWipeAction', 
               'Update-MgBetaDeviceAppManagementWindowsManagedAppProtection', 
               'Update-MgBetaDeviceAppManagementWindowsManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignment', 
               'Update-MgBetaUserDeviceEnrollmentConfiguration', 
               'Update-MgBetaUserDeviceEnrollmentConfigurationAssignment', 
               'Update-MgBetaUserDeviceManagementTroubleshootingEvent', 
               'Update-MgBetaUserManagedDevice', 
               'Update-MgBetaUserManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Update-MgBetaUserManagedDeviceCategory', 
               'Update-MgBetaUserManagedDeviceCompliancePolicyState', 
               'Update-MgBetaUserManagedDeviceConfigurationState', 
               'Update-MgBetaUserManagedDeviceHealthScriptState', 
               'Update-MgBetaUserManagedDeviceLogCollectionResponse', 
               'Update-MgBetaUserManagedDeviceMobileAppConfigurationState', 
               'Update-MgBetaUserManagedDeviceSecurityBaselineState', 
               'Update-MgBetaUserManagedDeviceSecurityBaselineStateSettingState', 
               'Update-MgBetaUserManagedDeviceWindowsProtectionState', 
               'Update-MgBetaUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Update-MgBetaUserMobileAppIntentAndState', 
               'Update-MgBetaUserMobileAppTroubleshootingEvent', 
               'Update-MgBetaUserMobileAppTroubleshootingEventAppLogCollectionRequest'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 
               'Clear-MgBetaDeviceAppMgtWindowsInformationProtectionDeviceRegistration', 
               'Get-MgBetaDeviceAppMgt', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtection', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppMgtDefaultManagedAppProtection', 
               'Get-MgBetaDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppMgtDefaultManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppMgtDefaultManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppMgtEnterpriseCodeSigningCertificate', 
               'Get-MgBetaDeviceAppMgtEnterpriseCodeSigningCertificateCount', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfiguration', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationAssignment', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationCount', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationDeviceStatusCount', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationGroupAssignmentCount', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationUserStatus', 
               'Get-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationUserStatusCount', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtection', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Get-MgBetaDeviceAppMgtManagedAppPolicy', 
               'Get-MgBetaDeviceAppMgtManagedAppPolicyCount', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistration', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationCount', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationOperation', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationOperationCount', 
               'Get-MgBetaDeviceAppMgtManagedAppRegistrationUserIdGraphWPreFlaggedAppRegistration', 
               'Get-MgBetaDeviceAppMgtManagedAppStatus', 
               'Get-MgBetaDeviceAppMgtManagedAppStatusCount', 
               'Get-MgBetaDeviceAppMgtManagedEBook', 
               'Get-MgBetaDeviceAppMgtManagedEBookAssignment', 
               'Get-MgBetaDeviceAppMgtManagedEBookAssignmentCount', 
               'Get-MgBetaDeviceAppMgtManagedEBookCategory', 
               'Get-MgBetaDeviceAppMgtManagedEBookCategoryCount', 
               'Get-MgBetaDeviceAppMgtManagedEBookCount', 
               'Get-MgBetaDeviceAppMgtManagedEBookDeviceState', 
               'Get-MgBetaDeviceAppMgtManagedEBookDeviceStateCount', 
               'Get-MgBetaDeviceAppMgtManagedEBookInstallSummary', 
               'Get-MgBetaDeviceAppMgtManagedEBookUserStateSummary', 
               'Get-MgBetaDeviceAppMgtManagedEBookUserStateSummaryCount', 
               'Get-MgBetaDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Get-MgBetaDeviceAppMgtManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyCount', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgBetaDeviceAppMgtMobileApp', 
               'Get-MgBetaDeviceAppMgtMobileAppAsManagedMobileLobApp', 
               'Get-MgBetaDeviceAppMgtMobileAppAsMobileLobApp', 
               'Get-MgBetaDeviceAppMgtMobileAppAssignment', 
               'Get-MgBetaDeviceAppMgtMobileAppAssignmentCount', 
               'Get-MgBetaDeviceAppMgtMobileAppCategory', 
               'Get-MgBetaDeviceAppMgtMobileAppCategoryCount', 
               'Get-MgBetaDeviceAppMgtMobileAppConfiguration', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignment', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationCount', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatusCount', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusCount', 
               'Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Get-MgBetaDeviceAppMgtMobileAppCount', 
               'Get-MgBetaDeviceAppMgtMobileAppCountAsManagedMobileLobApp', 
               'Get-MgBetaDeviceAppMgtMobileAppCountAsMobileLobApp', 
               'Get-MgBetaDeviceAppMgtMobileAppRelationship', 
               'Get-MgBetaDeviceAppMgtMobileAppRelationshipCount', 
               'Get-MgBetaDeviceAppMgtPolicySet', 
               'Get-MgBetaDeviceAppMgtPolicySetAssignment', 
               'Get-MgBetaDeviceAppMgtPolicySetAssignmentCount', 
               'Get-MgBetaDeviceAppMgtPolicySetCount', 
               'Get-MgBetaDeviceAppMgtPolicySetItem', 
               'Get-MgBetaDeviceAppMgtPolicySetItemCount', 
               'Get-MgBetaDeviceAppMgtSymantecCodeSigningCertificate', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfiguration', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAppCount', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationCount', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSetting', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSettingCount', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSettingDefinition', 
               'Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSettingDefinitionCount', 
               'Get-MgBetaDeviceAppMgtTask', 'Get-MgBetaDeviceAppMgtTaskCount', 
               'Get-MgBetaDeviceAppMgtVppToken', 
               'Get-MgBetaDeviceAppMgtVppTokenCount', 
               'Get-MgBetaDeviceAppMgtVppTokenLicenseGraphFPreApp', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicy', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicyAssignment', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicyCount', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicyDeploySummary', 
               'Get-MgBetaDeviceAppMgtWdacSupplementalPolicyDeviceStatus', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionDeviceRegistration', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionDeviceRegistrationCount', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicy', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyAssignmentCount', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyCount', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionWipeAction', 
               'Get-MgBetaDeviceAppMgtWindowInformationProtectionWipeActionCount', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtection', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtectionApp', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtectionAppCount', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtectionAssignment', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtectionAssignmentCount', 
               'Get-MgBetaDeviceAppMgtWindowManagedAppProtectionCount', 
               'Get-MgBetaDeviceAppMgtWindowManagementApp', 
               'New-MgBetaDeviceAppMgtAndroidManagedAppProtection', 
               'New-MgBetaDeviceAppMgtAndroidManagedAppProtectionApp', 
               'New-MgBetaDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'New-MgBetaDeviceAppMgtDefaultManagedAppProtection', 
               'New-MgBetaDeviceAppMgtDefaultManagedAppProtectionApp', 
               'New-MgBetaDeviceAppMgtEnterpriseCodeSigningCertificate', 
               'New-MgBetaDeviceAppMgtiOSLobAppProvisioningConfiguration', 
               'New-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationAssignment', 
               'New-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationDeviceStatus', 
               'New-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationGroupAssignment', 
               'New-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationUserStatus', 
               'New-MgBetaDeviceAppMgtiOSManagedAppProtection', 
               'New-MgBetaDeviceAppMgtiOSManagedAppProtectionApp', 
               'New-MgBetaDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'New-MgBetaDeviceAppMgtManagedAppPolicy', 
               'New-MgBetaDeviceAppMgtManagedAppRegistration', 
               'New-MgBetaDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'New-MgBetaDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'New-MgBetaDeviceAppMgtManagedAppRegistrationOperation', 
               'New-MgBetaDeviceAppMgtManagedAppStatus', 
               'New-MgBetaDeviceAppMgtManagedEBook', 
               'New-MgBetaDeviceAppMgtManagedEBookAssignment', 
               'New-MgBetaDeviceAppMgtManagedEBookCategory', 
               'New-MgBetaDeviceAppMgtManagedEBookDeviceState', 
               'New-MgBetaDeviceAppMgtManagedEBookUserStateSummary', 
               'New-MgBetaDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'New-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'New-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'New-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgBetaDeviceAppMgtMobileApp', 
               'New-MgBetaDeviceAppMgtMobileAppAssignment', 
               'New-MgBetaDeviceAppMgtMobileAppCategory', 
               'New-MgBetaDeviceAppMgtMobileAppConfiguration', 
               'New-MgBetaDeviceAppMgtMobileAppConfigurationAssignment', 
               'New-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'New-MgBetaDeviceAppMgtMobileAppConfigurationUserStatus', 
               'New-MgBetaDeviceAppMgtMobileAppRelationship', 
               'New-MgBetaDeviceAppMgtPolicySet', 
               'New-MgBetaDeviceAppMgtPolicySetAssignment', 
               'New-MgBetaDeviceAppMgtPolicySetItem', 
               'New-MgBetaDeviceAppMgtTargetedManagedAppConfiguration', 
               'New-MgBetaDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'New-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'New-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSetting', 
               'New-MgBetaDeviceAppMgtTask', 'New-MgBetaDeviceAppMgtVppToken', 
               'New-MgBetaDeviceAppMgtWdacSupplementalPolicy', 
               'New-MgBetaDeviceAppMgtWdacSupplementalPolicyAssignment', 
               'New-MgBetaDeviceAppMgtWdacSupplementalPolicyDeviceStatus', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionDeviceRegistration', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionPolicy', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgBetaDeviceAppMgtWindowInformationProtectionWipeAction', 
               'New-MgBetaDeviceAppMgtWindowManagedAppProtection', 
               'New-MgBetaDeviceAppMgtWindowManagedAppProtectionApp', 
               'New-MgBetaDeviceAppMgtWindowManagedAppProtectionAssignment', 
               'Remove-MgBetaDeviceAppMgtAndroidManagedAppProtection', 
               'Remove-MgBetaDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Remove-MgBetaDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppMgtDefaultManagedAppProtection', 
               'Remove-MgBetaDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppMgtEnterpriseCodeSigningCertificate', 
               'Remove-MgBetaDeviceAppMgtiOSLobAppProvisioningConfiguration', 
               'Remove-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationAssignment', 
               'Remove-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Remove-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Remove-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationUserStatus', 
               'Remove-MgBetaDeviceAppMgtiOSManagedAppProtection', 
               'Remove-MgBetaDeviceAppMgtiOSManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Remove-MgBetaDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Remove-MgBetaDeviceAppMgtManagedAppPolicy', 
               'Remove-MgBetaDeviceAppMgtManagedAppRegistration', 
               'Remove-MgBetaDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Remove-MgBetaDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Remove-MgBetaDeviceAppMgtManagedAppRegistrationOperation', 
               'Remove-MgBetaDeviceAppMgtManagedAppStatus', 
               'Remove-MgBetaDeviceAppMgtManagedEBook', 
               'Remove-MgBetaDeviceAppMgtManagedEBookAssignment', 
               'Remove-MgBetaDeviceAppMgtManagedEBookCategory', 
               'Remove-MgBetaDeviceAppMgtManagedEBookDeviceState', 
               'Remove-MgBetaDeviceAppMgtManagedEBookInstallSummary', 
               'Remove-MgBetaDeviceAppMgtManagedEBookUserStateSummary', 
               'Remove-MgBetaDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Remove-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Remove-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgBetaDeviceAppMgtMobileApp', 
               'Remove-MgBetaDeviceAppMgtMobileAppAssignment', 
               'Remove-MgBetaDeviceAppMgtMobileAppCategory', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfiguration', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfigurationAssignment', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Remove-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Remove-MgBetaDeviceAppMgtMobileAppRelationship', 
               'Remove-MgBetaDeviceAppMgtPolicySet', 
               'Remove-MgBetaDeviceAppMgtPolicySetAssignment', 
               'Remove-MgBetaDeviceAppMgtPolicySetItem', 
               'Remove-MgBetaDeviceAppMgtSymantecCodeSigningCertificate', 
               'Remove-MgBetaDeviceAppMgtTargetedManagedAppConfiguration', 
               'Remove-MgBetaDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Remove-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Remove-MgBetaDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSetting', 
               'Remove-MgBetaDeviceAppMgtTask', 
               'Remove-MgBetaDeviceAppMgtVppToken', 
               'Remove-MgBetaDeviceAppMgtWdacSupplementalPolicy', 
               'Remove-MgBetaDeviceAppMgtWdacSupplementalPolicyAssignment', 
               'Remove-MgBetaDeviceAppMgtWdacSupplementalPolicyDeploySummary', 
               'Remove-MgBetaDeviceAppMgtWdacSupplementalPolicyDeviceStatus', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionDeviceRegistration', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionPolicy', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgBetaDeviceAppMgtWindowInformationProtectionWipeAction', 
               'Remove-MgBetaDeviceAppMgtWindowManagedAppProtection', 
               'Remove-MgBetaDeviceAppMgtWindowManagedAppProtectionApp', 
               'Remove-MgBetaDeviceAppMgtWindowManagedAppProtectionAssignment', 
               'Rename-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSetting', 
               'Revoke-MgBetaDeviceAppMgtVppTokenLicense', 
               'Set-MgBetaDeviceAppMgtIosLobAppProvisioningConfiguration', 
               'Set-MgBetaDeviceAppMgtManagedEBook', 
               'Set-MgBetaDeviceAppMgtMobileApp', 
               'Set-MgBetaDeviceAppMgtMobileAppConfiguration', 
               'Set-MgBetaDeviceAppMgtTargetedManagedAppConfiguration', 
               'Set-MgBetaDeviceAppMgtWdacSupplementalPolicy', 
               'Set-MgBetaDeviceAppMgtWindowsManagedAppProtection', 
               'Sync-MgBetaDeviceAppMgtMicrosoftStoreGraphFPreBusinessApp', 
               'Sync-MgBetaDeviceAppMgtVppTokenLicense', 
               'Sync-MgBetaDeviceAppMgtVppTokenLicenseCount', 
               'Test-MgBetaDeviceAppMgtMobileAppXml', 'Update-MgBetaDeviceAppMgt', 
               'Update-MgBetaDeviceAppMgtAndroidManagedAppProtection', 
               'Update-MgBetaDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Update-MgBetaDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppMgtDefaultManagedAppProtection', 
               'Update-MgBetaDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppMgtEnterpriseCodeSigningCertificate', 
               'Update-MgBetaDeviceAppMgtiOSLobAppProvisioningConfiguration', 
               'Update-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationAssignment', 
               'Update-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationDeviceStatus', 
               'Update-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationGroupAssignment', 
               'Update-MgBetaDeviceAppMgtiOSLobAppProvisioningConfigurationUserStatus', 
               'Update-MgBetaDeviceAppMgtiOSManagedAppProtection', 
               'Update-MgBetaDeviceAppMgtiOSManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Update-MgBetaDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Update-MgBetaDeviceAppMgtManagedAppPolicy', 
               'Update-MgBetaDeviceAppMgtManagedAppRegistration', 
               'Update-MgBetaDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Update-MgBetaDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Update-MgBetaDeviceAppMgtManagedAppRegistrationOperation', 
               'Update-MgBetaDeviceAppMgtManagedAppStatus', 
               'Update-MgBetaDeviceAppMgtManagedEBook', 
               'Update-MgBetaDeviceAppMgtManagedEBookAssignment', 
               'Update-MgBetaDeviceAppMgtManagedEBookCategory', 
               'Update-MgBetaDeviceAppMgtManagedEBookDeviceState', 
               'Update-MgBetaDeviceAppMgtManagedEBookInstallSummary', 
               'Update-MgBetaDeviceAppMgtManagedEBookUserStateSummary', 
               'Update-MgBetaDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Update-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Update-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Update-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgBetaDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgBetaDeviceAppMgtMobileApp', 
               'Update-MgBetaDeviceAppMgtMobileAppAssignment', 
               'Update-MgBetaDeviceAppMgtMobileAppCategory', 
               'Update-MgBetaDeviceAppMgtMobileAppConfiguration', 
               'Update-MgBetaDeviceAppMgtMobileAppConfigurationAssignment', 
               'Update-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Update-MgBetaDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgBetaDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Update-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Update-MgBetaDeviceAppMgtMobileAppRelationship', 
               'Update-MgBetaDeviceAppMgtMultipleMobileAppRelationship', 
               'Update-MgBetaDeviceAppMgtMultiplePolicySet', 
               'Update-MgBetaDeviceAppMgtPolicySet', 
               'Update-MgBetaDeviceAppMgtPolicySetAssignment', 
               'Update-MgBetaDeviceAppMgtPolicySetItem', 
               'Update-MgBetaDeviceAppMgtSymantecCodeSigningCertificate', 
               'Update-MgBetaDeviceAppMgtTargetedManagedAppConfiguration', 
               'Update-MgBetaDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Update-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Update-MgBetaDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgBetaDeviceAppMgtTargetedManagedAppConfigurationSetting', 
               'Update-MgBetaDeviceAppMgtTask', 
               'Update-MgBetaDeviceAppMgtTaskStatus', 
               'Update-MgBetaDeviceAppMgtVppToken', 
               'Update-MgBetaDeviceAppMgtWdacSupplementalPolicy', 
               'Update-MgBetaDeviceAppMgtWdacSupplementalPolicyAssignment', 
               'Update-MgBetaDeviceAppMgtWdacSupplementalPolicyDeploySummary', 
               'Update-MgBetaDeviceAppMgtWdacSupplementalPolicyDeviceStatus', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionDeviceRegistration', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionPolicy', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgBetaDeviceAppMgtWindowInformationProtectionWipeAction', 
               'Update-MgBetaDeviceAppMgtWindowManagedAppProtection', 
               'Update-MgBetaDeviceAppMgtWindowManagedAppProtectionApp', 
               'Update-MgBetaDeviceAppMgtWindowManagedAppProtectionAssignment'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInpQYJKoZIhvcNAQcCoIInljCCJ5ICAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBAlX37Z1sVSb82
# PpdxgVFxk5XKPH9rPO7jE1Rf5NMwfaCCDYUwggYDMIID66ADAgECAhMzAAADTU6R
# phoosHiPAAAAAANNMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI4WhcNMjQwMzE0MTg0MzI4WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDUKPcKGVa6cboGQU03ONbUKyl4WpH6Q2Xo9cP3RhXTOa6C6THltd2RfnjlUQG+
# Mwoy93iGmGKEMF/jyO2XdiwMP427j90C/PMY/d5vY31sx+udtbif7GCJ7jJ1vLzd
# j28zV4r0FGG6yEv+tUNelTIsFmmSb0FUiJtU4r5sfCThvg8dI/F9Hh6xMZoVti+k
# bVla+hlG8bf4s00VTw4uAZhjGTFCYFRytKJ3/mteg2qnwvHDOgV7QSdV5dWdd0+x
# zcuG0qgd3oCCAjH8ZmjmowkHUe4dUmbcZfXsgWlOfc6DG7JS+DeJak1DvabamYqH
# g1AUeZ0+skpkwrKwXTFwBRltAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUId2Img2Sp05U6XI04jli2KohL+8w
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMDUxNzAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# ACMET8WuzLrDwexuTUZe9v2xrW8WGUPRQVmyJ1b/BzKYBZ5aU4Qvh5LzZe9jOExD
# YUlKb/Y73lqIIfUcEO/6W3b+7t1P9m9M1xPrZv5cfnSCguooPDq4rQe/iCdNDwHT
# 6XYW6yetxTJMOo4tUDbSS0YiZr7Mab2wkjgNFa0jRFheS9daTS1oJ/z5bNlGinxq
# 2v8azSP/GcH/t8eTrHQfcax3WbPELoGHIbryrSUaOCphsnCNUqUN5FbEMlat5MuY
# 94rGMJnq1IEd6S8ngK6C8E9SWpGEO3NDa0NlAViorpGfI0NYIbdynyOB846aWAjN
# fgThIcdzdWFvAl/6ktWXLETn8u/lYQyWGmul3yz+w06puIPD9p4KPiWBkCesKDHv
# XLrT3BbLZ8dKqSOV8DtzLFAfc9qAsNiG8EoathluJBsbyFbpebadKlErFidAX8KE
# usk8htHqiSkNxydamL/tKfx3V/vDAoQE59ysv4r3pE+zdyfMairvkFNNw7cPn1kH
# Gcww9dFSY2QwAxhMzmoM0G+M+YvBnBu5wjfxNrMRilRbxM6Cj9hKFh0YTwba6M7z
# ntHHpX3d+nabjFm/TnMRROOgIXJzYbzKKaO2g1kWeyG2QtvIR147zlrbQD4X10Ab
# rRg9CpwW7xYxywezj+iNAc+QmFzR94dzJkEPUSCJPsTFMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGXYwghlyAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAANNTpGmGiiweI8AAAAA
# A00wDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIJ++
# uBNi/4RAfNYyodDcGyygvqr6OG7h63h3QMrZhj4GMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAGk8ib/rf3tzAcp0KSmvGHM8pFPg2QTn975o+
# qf+gQ8sqA9aA0VBZEGhA3hsM/dpIRvuECXlkSbQQ9iCwYrQR4JDbkgN6YWaAbRuR
# vldSOlt4T7Za6uGYc80T/cPPwmekTKKCESVvR9fO1G9LolYxGhWS+pq1OW4nz8Th
# zUoFD7KHXR4WKSPou6e2dqg+UhBkyHF2p/cwP2h11tge+4ldaFZ6pyt2gjSeovFs
# yPIvnckMMMk+gRxfyESYIcmCqfQsDZFF6cQUhZdK1LzDLaXimGDhnjVeZ13mkskW
# rvoSOcBOwmD17NuiX2WzXMmLPxPUev5+OB94AgTDkWMQahEnhKGCFwAwghb8Bgor
# BgEEAYI3AwMBMYIW7DCCFugGCSqGSIb3DQEHAqCCFtkwghbVAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFRBgsqhkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCAh/jVmMDYJRqh1WiZOeepx6ZgNmQFMqc+S
# elQT0z3KiAIGZK/6RN8mGBMyMDIzMDcyNjE5MTg1OS44MDdaMASAAgH0oIHQpIHN
# MIHKMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQL
# ExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMg
# VFNTIEVTTjpENkJELUUzRTctMTY4NTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZaCCEVcwggcMMIIE9KADAgECAhMzAAABx/sAoEpb8ifcAAEA
# AAHHMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MB4XDTIyMTEwNDE5MDEzNVoXDTI0MDIwMjE5MDEzNVowgcoxCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVy
# aWNhIE9wZXJhdGlvbnMxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOkQ2QkQtRTNF
# Ny0xNjg1MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIIC
# IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAr0LcVtnatNFMBrQTtG9P8ISA
# PyyGmxNfhEzaOVlt088pBUFAIasmN/eOijE6Ucaf3c2bVnN/02ih0smSqYkm5P3Z
# wU7ZW202b6cPDJjXcrjJj0qfnuccBtE3WU0vZ8CiQD7qrKxeF8YBNcS+PVtvsqhd
# 5YW6AwhWqhjw1mYuLetF5b6aPif/3RzlyqG3SV7QPiSJends7gG435Rsy1HJ4Xnq
# ztOJR41I0j3EQ05JMF5QNRi7kT6vXTT+MHVj27FVQ7bef/U+2EAbFj2X2AOWbvgl
# YaYnM3m/I/OWDHUgGw8KIdsDh3W1eusnF2D7oenGgtahs+S1G5Uolf5ESg/9Z+38
# rhQwLgokY5k6p8k5arYWtszdJK6JiIRl843H74k7+QqlT2LbAQPq8ivQv0gdclW2
# aJun1KrW+v52R3vAHCOtbUmxvD1eNGHqGqLagtlq9UFXKXuXnqXJqruCYmfwdFMD
# 0UP6ii1lFdeKL87PdjdAwyCiVcCEoLnvDzyvjNjxtkTdz6R4yF1N/X4PSQH4Flgs
# lyBIXggaSlPtvPuxAtuac/ITj4k0IRShGiYLBM2Dw6oesLOoxe07OUPO+qXXOcJM
# VHhE0MlhhnxfN2B1JWFPWwQ6ooWiqAOQDqzcDx+79shxA1Cx0K70eOBplMog27gY
# oLpBv7nRz4tHqoTyvA0CAwEAAaOCATYwggEyMB0GA1UdDgQWBBQFUNLdHD7BAF/V
# U/X/eEHLiUSSIDAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNV
# HR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2Ny
# bC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
# KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAy
# MDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0G
# CSqGSIb3DQEBCwUAA4ICAQDQy5c8ogP0y8xAsLVca07wWy1mT+nqYgAFnz2972kN
# O+KJ7AE4f+SVbvOnkeeuOPq3xc+6TS8g3FuKKYEwYqvnRHxX58tjlscZsZeKnu7f
# GNUlpNT9bOQFHWALURuoXp8TLHhxj3PEq9jzFYBP2YNMLol70ojY1qpze3nMMJfp
# durdBBpaOLlJmRNTLhxd+RJGJQbY1XAcx6p/FigwqBasSDUxp+0yFPEBB9uBE3KI
# LAtq6fczGp4EMeon6YmkyCGAtXMKDFQQgdP/ITe7VghAVbPTVlP3hY1dFgc+t8YK
# 2obFSFVKslkASATDHulCMht+WrIsukclEUP9DaMmpq7S0RLODMicI6PtqqGOhdna
# RltA0d+Wf+0tPt9SUVtrPJyO7WMPKbykCRXzmHK06zr0kn1YiUYNXCsOgaHF5ImO
# 2ZwQ54UE1I55jjUdldyjy/UPJgxRm9NyXeO7adYr8K8f6Q2nPF0vWqFG7ewwaAl5
# ClKerzshfhB8zujVR0d1Ra7Z01lnXYhWuPqVZayFl7JHr6i6huhpU6BQ6/VgY0cB
# iksX4mNM+ISY81T1RYt7fWATNu/zkjINczipzbfg5S+3fCAo8gVB6+6A5L0vBg39
# dsFITv6MWJuQ8ZZy7fwlFBZE4d5IFbRudakNwKGdyLGM2otaNq7wm3ku7x41UGAm
# kDCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQEL
# BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNV
# BAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4X
# DTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM
# 57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm
# 95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzB
# RMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBb
# fowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCO
# Mcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYw
# XE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW
# /aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/w
# EPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPK
# Z6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2
# BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfH
# CBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYB
# BAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8v
# BO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYM
# KwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEF
# BQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBW
# BgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUH
# AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
# L2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsF
# AAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518Jx
# Nj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+
# iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2
# pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefw
# C2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7
# T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFO
# Ry3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhL
# mm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3L
# wUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5
# m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE
# 0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLOMIICNwIB
# ATCB+KGB0KSBzTCByjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEmMCQGA1UE
# CxMdVGhhbGVzIFRTUyBFU046RDZCRC1FM0U3LTE2ODUxJTAjBgNVBAMTHE1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAOIASP0JSbv5
# R23wxciQivHyckYooIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTAwDQYJKoZIhvcNAQEFBQACBQDoa5p0MCIYDzIwMjMwNzI2MjExMzI0WhgPMjAy
# MzA3MjcyMTEzMjRaMHcwPQYKKwYBBAGEWQoEATEvMC0wCgIFAOhrmnQCAQAwCgIB
# AAICFLsCAf8wBwIBAAICEcMwCgIFAOhs6/QCAQAwNgYKKwYBBAGEWQoEAjEoMCYw
# DAYKKwYBBAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0B
# AQUFAAOBgQAX3je+QAkCf/2fVB2nm7+TZv7BZqmEpQ2VednJXB4L8YdoR0K4SlFe
# Yj+e+XACb4KNiQYQHMADHvezG5Ldp9mVoa6uhm2KemJhRQzB1qOBcPcSBtPf3SPr
# 3Bmt1XMCM8zp8ejpIzizh68rFgQrKvyF7NShE5r5OUsEFGIHmnl0czGCBA0wggQJ
# AgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAk
# BgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABx/sAoEpb
# 8ifcAAEAAAHHMA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
# hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIKFaqkhjxAWerjZnfnC0y7dLvBaaG/h9
# XZ3uIXJYgQMHMIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQgR+fl2+JSskUL
# OeVYLbeMgk7HdIbREmAsjwtcy6MJkskwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
# dGFtcCBQQ0EgMjAxMAITMwAAAcf7AKBKW/In3AABAAABxzAiBCCQsCecfk8iLQkH
# DeUtycaJGo14oBdzTTWdQ0IN8HALujANBgkqhkiG9w0BAQsFAASCAgAFHsHMHUm7
# 2ISBTbMKNuf7BT6L/qDLYGGlC4OJ9baQNvPMfMa6zNtF7MAIklKF8jqjXnaWelMo
# aHP2NQYiThkgamGyLWKpyqlr9NRi5Mv4ZCPm8kLrNY3O9N9BaBiolzuN9w7xMUWV
# AzGdExojSS8S8gZvWUxa2VuRfnHk+9XcabVZQu6K+QILZqhRMWqJppKfWh70LZDe
# dHoSFmE1kfk+LsyEjC8lxsGJ/cawd5LXN+nmteBV2mxTJS05PDB1WXXJp+s687ug
# sIEAeu+VA0oBv5z4hhwTbFp0v8tLdNzBbD6HkSx5u3S5N5xB+ygbi/ODDwXy3EuO
# hQqi7yPFn/kzYKGPfOXEF/NdaGdCfLo058nqdGhocC6Nx5wunXwa7/G5EXI+vdbi
# 8PdcWjsO65CfD7XfVdEapl/x7AQXwW5KXPJYoBrNaM9Ht96CWbU/65N+fL9udB00
# 5LJ246vIW48UvfJlE/Y3tpxdG29fUn/VmHRIwDVZDz94ezlrHXSFEjT2A/9pfuFL
# jgs5nRGxNtGkv3nDNt9/hYo0B1q/zVRhlm/aNI87YdXmHZcCQ+kohhnCcd+wY/m/
# KNXezdB1yTGm9N5kkHM7eQGiZvMB29L3e97PIHwhLjHHRzUSQqUmCjRVL6GxbCBP
# 91j+dmPLMHnkjkyk9MbgzVLaq/ghdmZWuw==
# SIG # End signature block
