#
# Module manifest for module 'Microsoft.Graph.Beta.CloudCommunications'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/26/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.CloudCommunications.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f07aeb05-f355-4116-a587-f725d4797aa2'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.2.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.CloudCommunications.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.CloudCommunications.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaCommunicationCallLargeGalleryView', 
               'Clear-MgBetaCommunicationPresence', 
               'Clear-MgBetaCommunicationPresenceUserPreferredPresence', 
               'Get-MgBetaCommunicationCall', 
               'Get-MgBetaCommunicationCallAudioRoutingGroup', 
               'Get-MgBetaCommunicationCallAudioRoutingGroupCount', 
               'Get-MgBetaCommunicationCallContentSharingSession', 
               'Get-MgBetaCommunicationCallContentSharingSessionCount', 
               'Get-MgBetaCommunicationCallCount', 
               'Get-MgBetaCommunicationCallOperation', 
               'Get-MgBetaCommunicationCallOperationCount', 
               'Get-MgBetaCommunicationCallParticipant', 
               'Get-MgBetaCommunicationCallParticipantCount', 
               'Get-MgBetaCommunicationCallRecord', 
               'Get-MgBetaCommunicationCallRecordCount', 
               'Get-MgBetaCommunicationCallRecordPstnBlockedUserLog', 
               'Get-MgBetaCommunicationCallRecordPstnOnlineMeetingDialoutReport', 
               'Get-MgBetaCommunicationCallRecordSession', 
               'Get-MgBetaCommunicationCallRecordSessionCount', 
               'Get-MgBetaCommunicationCallRecordSessionSegmentCount', 
               'Get-MgBetaCommunicationCallRecordSmLog', 
               'Get-MgBetaCommunicationOnlineMeeting', 
               'Get-MgBetaCommunicationOnlineMeetingAlternativeRecording', 
               'Get-MgBetaCommunicationOnlineMeetingAttendanceReport', 
               'Get-MgBetaCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Get-MgBetaCommunicationOnlineMeetingAttendanceReportAttendanceRecordCount', 
               'Get-MgBetaCommunicationOnlineMeetingAttendanceReportCount', 
               'Get-MgBetaCommunicationOnlineMeetingAttendeeReport', 
               'Get-MgBetaCommunicationOnlineMeetingBroadcastRecording', 
               'Get-MgBetaCommunicationOnlineMeetingCount', 
               'Get-MgBetaCommunicationOnlineMeetingRecording', 
               'Get-MgBetaCommunicationOnlineMeetingRecordingContent', 
               'Get-MgBetaCommunicationOnlineMeetingRecordingCount', 
               'Get-MgBetaCommunicationOnlineMeetingRegistration', 
               'Get-MgBetaCommunicationOnlineMeetingRegistrationCustomQuestion', 
               'Get-MgBetaCommunicationOnlineMeetingRegistrationCustomQuestionCount', 
               'Get-MgBetaCommunicationOnlineMeetingRegistrationRegistrant', 
               'Get-MgBetaCommunicationOnlineMeetingRegistrationRegistrantCount', 
               'Get-MgBetaCommunicationOnlineMeetingTranscript', 
               'Get-MgBetaCommunicationOnlineMeetingTranscriptContent', 
               'Get-MgBetaCommunicationOnlineMeetingTranscriptCount', 
               'Get-MgBetaCommunicationOnlineMeetingTranscriptMetadataContent', 
               'Get-MgBetaCommunicationOnlineMeetingVirtualAppointment', 
               'Get-MgBetaCommunicationOnlineMeetingVirtualAppointmentJoinWebUrl', 
               'Get-MgBetaCommunicationPresence', 
               'Get-MgBetaCommunicationPresenceByUserId', 
               'Get-MgBetaCommunicationPresenceCount', 
               'Get-MgBetaUserOnlineMeeting', 
               'Get-MgBetaUserOnlineMeetingAlternativeRecording', 
               'Get-MgBetaUserOnlineMeetingAttendanceReport', 
               'Get-MgBetaUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Get-MgBetaUserOnlineMeetingAttendanceReportAttendanceRecordCount', 
               'Get-MgBetaUserOnlineMeetingAttendanceReportCount', 
               'Get-MgBetaUserOnlineMeetingAttendeeReport', 
               'Get-MgBetaUserOnlineMeetingBroadcastRecording', 
               'Get-MgBetaUserOnlineMeetingCount', 
               'Get-MgBetaUserOnlineMeetingRecording', 
               'Get-MgBetaUserOnlineMeetingRecordingContent', 
               'Get-MgBetaUserOnlineMeetingRecordingCount', 
               'Get-MgBetaUserOnlineMeetingRegistration', 
               'Get-MgBetaUserOnlineMeetingRegistrationCustomQuestion', 
               'Get-MgBetaUserOnlineMeetingRegistrationCustomQuestionCount', 
               'Get-MgBetaUserOnlineMeetingRegistrationRegistrant', 
               'Get-MgBetaUserOnlineMeetingRegistrationRegistrantCount', 
               'Get-MgBetaUserOnlineMeetingTranscript', 
               'Get-MgBetaUserOnlineMeetingTranscriptContent', 
               'Get-MgBetaUserOnlineMeetingTranscriptCount', 
               'Get-MgBetaUserOnlineMeetingTranscriptMetadataContent', 
               'Get-MgBetaUserOnlineMeetingVirtualAppointment', 
               'Get-MgBetaUserPresence', 'Invoke-MgBetaAnswerCommunicationCall', 
               'Invoke-MgBetaCreateOrGetCommunicationOnlineMeeting', 
               'Invoke-MgBetaInviteCommunicationCallParticipant', 
               'Invoke-MgBetaKeepCommunicationCallAlive', 
               'Invoke-MgBetaLogCommunicationCallTeleconferenceDeviceQuality', 
               'Invoke-MgBetaMuteAllCommunicationCallParticipant', 
               'Invoke-MgBetaMuteCommunicationCall', 
               'Invoke-MgBetaMuteCommunicationCallParticipant', 
               'Invoke-MgBetaPlayCommunicationCallPrompt', 
               'Invoke-MgBetaRecordCommunicationCall', 
               'Invoke-MgBetaRecordCommunicationCallResponse', 
               'Invoke-MgBetaRedirectCommunicationCall', 
               'Invoke-MgBetaRejectCommunicationCall', 
               'Invoke-MgBetaSubscribeCommunicationCallToTone', 
               'Invoke-MgBetaUnmuteCommunicationCall', 
               'Move-MgBetaCommunicationCall', 'New-MgBetaCommunicationCall', 
               'New-MgBetaCommunicationCallAudioRoutingGroup', 
               'New-MgBetaCommunicationCallContentSharingSession', 
               'New-MgBetaCommunicationCallOperation', 
               'New-MgBetaCommunicationCallParticipant', 
               'New-MgBetaCommunicationCallRecordSession', 
               'New-MgBetaCommunicationOnlineMeeting', 
               'New-MgBetaCommunicationOnlineMeetingAttendanceReport', 
               'New-MgBetaCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'New-MgBetaCommunicationOnlineMeetingRecording', 
               'New-MgBetaCommunicationOnlineMeetingRegistrationCustomQuestion', 
               'New-MgBetaCommunicationOnlineMeetingRegistrationRegistrant', 
               'New-MgBetaCommunicationOnlineMeetingTranscript', 
               'New-MgBetaCommunicationPresence', 'New-MgBetaUserOnlineMeeting', 
               'New-MgBetaUserOnlineMeetingAttendanceReport', 
               'New-MgBetaUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'New-MgBetaUserOnlineMeetingRecording', 
               'New-MgBetaUserOnlineMeetingRegistrationCustomQuestion', 
               'New-MgBetaUserOnlineMeetingRegistrationRegistrant', 
               'New-MgBetaUserOnlineMeetingTranscript', 
               'Remove-MgBetaCommunicationCall', 
               'Remove-MgBetaCommunicationCallAudioRoutingGroup', 
               'Remove-MgBetaCommunicationCallContentSharingSession', 
               'Remove-MgBetaCommunicationCallOperation', 
               'Remove-MgBetaCommunicationCallParticipant', 
               'Remove-MgBetaCommunicationCallRecordSession', 
               'Remove-MgBetaCommunicationOnlineMeeting', 
               'Remove-MgBetaCommunicationOnlineMeetingAttendanceReport', 
               'Remove-MgBetaCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Remove-MgBetaCommunicationOnlineMeetingRecording', 
               'Remove-MgBetaCommunicationOnlineMeetingRegistration', 
               'Remove-MgBetaCommunicationOnlineMeetingRegistrationCustomQuestion', 
               'Remove-MgBetaCommunicationOnlineMeetingRegistrationRegistrant', 
               'Remove-MgBetaCommunicationOnlineMeetingTranscript', 
               'Remove-MgBetaCommunicationOnlineMeetingVirtualAppointment', 
               'Remove-MgBetaCommunicationPresence', 
               'Remove-MgBetaUserOnlineMeeting', 
               'Remove-MgBetaUserOnlineMeetingAttendanceReport', 
               'Remove-MgBetaUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Remove-MgBetaUserOnlineMeetingRecording', 
               'Remove-MgBetaUserOnlineMeetingRegistration', 
               'Remove-MgBetaUserOnlineMeetingRegistrationCustomQuestion', 
               'Remove-MgBetaUserOnlineMeetingRegistrationRegistrant', 
               'Remove-MgBetaUserOnlineMeetingTranscript', 
               'Remove-MgBetaUserOnlineMeetingVirtualAppointment', 
               'Remove-MgBetaUserPresence', 
               'Rename-MgBetaCommunicationCallScreenSharingRole', 
               'Set-MgBetaCommunicationOnlineMeetingAlternativeRecording', 
               'Set-MgBetaCommunicationOnlineMeetingAttendeeReport', 
               'Set-MgBetaCommunicationOnlineMeetingBroadcastRecording', 
               'Set-MgBetaCommunicationOnlineMeetingRecording', 
               'Set-MgBetaCommunicationOnlineMeetingRecordingContent', 
               'Set-MgBetaCommunicationOnlineMeetingTranscriptContent', 
               'Set-MgBetaCommunicationOnlineMeetingTranscriptMetadataContent', 
               'Set-MgBetaCommunicationPresence', 
               'Set-MgBetaCommunicationPresenceStatusMessage', 
               'Set-MgBetaCommunicationPresenceUserPreferredPresence', 
               'Set-MgBetaUserOnlineMeetingAlternativeRecording', 
               'Set-MgBetaUserOnlineMeetingAttendeeReport', 
               'Set-MgBetaUserOnlineMeetingBroadcastRecording', 
               'Set-MgBetaUserOnlineMeetingRecording', 
               'Set-MgBetaUserOnlineMeetingRecordingContent', 
               'Set-MgBetaUserOnlineMeetingTranscriptContent', 
               'Set-MgBetaUserOnlineMeetingTranscriptMetadataContent', 
               'Start-MgBetaCommunicationCallParticipantHoldMusic', 
               'Stop-MgBetaCommunicationCallMediaProcessing', 
               'Stop-MgBetaCommunicationCallParticipantHoldMusic', 
               'Update-MgBetaCommunicationCallAudioRoutingGroup', 
               'Update-MgBetaCommunicationCallContentSharingSession', 
               'Update-MgBetaCommunicationCallOperation', 
               'Update-MgBetaCommunicationCallParticipant', 
               'Update-MgBetaCommunicationCallRecordingStatus', 
               'Update-MgBetaCommunicationCallRecordSession', 
               'Update-MgBetaCommunicationOnlineMeeting', 
               'Update-MgBetaCommunicationOnlineMeetingAttendanceReport', 
               'Update-MgBetaCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Update-MgBetaCommunicationOnlineMeetingRecording', 
               'Update-MgBetaCommunicationOnlineMeetingRegistration', 
               'Update-MgBetaCommunicationOnlineMeetingRegistrationCustomQuestion', 
               'Update-MgBetaCommunicationOnlineMeetingRegistrationRegistrant', 
               'Update-MgBetaCommunicationOnlineMeetingTranscript', 
               'Update-MgBetaCommunicationOnlineMeetingVirtualAppointment', 
               'Update-MgBetaCommunicationPresence', 
               'Update-MgBetaUserOnlineMeeting', 
               'Update-MgBetaUserOnlineMeetingAttendanceReport', 
               'Update-MgBetaUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Update-MgBetaUserOnlineMeetingRecording', 
               'Update-MgBetaUserOnlineMeetingRegistration', 
               'Update-MgBetaUserOnlineMeetingRegistrationCustomQuestion', 
               'Update-MgBetaUserOnlineMeetingRegistrationRegistrant', 
               'Update-MgBetaUserOnlineMeetingTranscript', 
               'Update-MgBetaUserOnlineMeetingVirtualAppointment', 
               'Update-MgBetaUserPresence'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInwAYJKoZIhvcNAQcCoIInsTCCJ60CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDxo7duWqOGQBWq
# wri4xjBPRGPzIi8c2e59ydqUDuUmU6CCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGaAwghmcAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEICXgy8WbVDjGDCJhNWQcn3s1
# bBXQNpM1jSvlNjDYHFvDMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAtD8P3rK96G3p8fDhX9MI5nABeiuH10775zS35i9DUZYOWaJAmgWlwvRE
# pF4d0OcdLwPU5mwkp1z5kdcOTi2DCwiDpCMXR87WyqrMvNJQZRh/E3zctr6c6YUv
# plqd/EV2fvz1lP4qQG/Hcz2+12hX8uTqZrwfxhXupG01nW4xKE2KGRIIJ5YNKWPX
# TqnsFM6S2A+lsoECHRiWvWgWfyHsNZzK+IKJ8LtVowR81pauGb55qwEjM5xyik+8
# OFNAH6pigweSpIESxkT7VTfnDFktQ67p55zb4ksDwyQh0Zav1+n8h27vh91G3MPE
# i63bfWN1cc1UsSw+XG4AYPAJ201+EqGCFyowghcmBgorBgEEAYI3AwMBMYIXFjCC
# FxIGCSqGSIb3DQEHAqCCFwMwghb/AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFXBgsq
# hkiG9w0BCRABBKCCAUYEggFCMIIBPgIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCDr+5Q2RMkhnJhJXFD5EnD35tJVwaekmZfuyOX1MVsrjwIGZLgfuKWT
# GBEyMDIzMDcyNjE5MTkwMC45WjAEgAIB9KCB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjo4
# NkRGLTRCQkMtOTMzNTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaCCEXswggcnMIIFD6ADAgECAhMzAAABtyEnGgeiKoZGAAEAAAG3MA0GCSqG
# SIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIyMDky
# MDIwMjIxNFoXDTIzMTIxNDIwMjIxNFowgdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046ODZERi00QkJD
# LTkzMzUxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDH/c9XUDQTZEwatxyXJcqY0HCS
# JQwIKb7MOLxyXtOp+d9kShpHJ9Fe6euTngNcDqDvvDbKKZ4z6VWfPuLP0YXTAjDT
# 0CV6FnZFjqf96biBLNX8zwYEya3Zs3clGM6wJaCAmMe9toJnaWzX9z9MuWdoETuP
# LFiGMmHjSWHIfmXyc16qr7r6uxvDZvCDEIvGWsr8fuXUhgTOVWBwcQhI1xfRDekM
# OwOtEml4yo6I0qVJqWjOBZlXnPfOTzXUofITnj9rS+/NUgWp/dg09fbXzR7/R9BQ
# JhNhxkcIsx5Cf/5gGXUtLOm4v1MDzJLAImuW6ZyAwTqGmHVpFdJVRuazdPpbUc/c
# 45Wh/boXRkyflojSjq+5kZ5c2EAOd37UkiQarBKU8wr+3Ou933b5bcd8uPD3q+r3
# OlEeXuJEmbB9eNSIcYZkUdkphGm7mCjk3Tu0P75bwH0MbhJyfdzS+C2FdSFsPDvs
# TTuoJY6waQjnzjk0IFiRfjOvyD8rmK3L+/S7u5XOu0vlPTBLtnaINDLiSKGAjIrl
# Wl0ufhZjiYsn4gmZtFSbCee9MvZP7REHumkEfTMQ1tadhdx1nm6JV4/bLu866xJT
# ZRwBL6RYXIKDJ4spTU4k2cy8FI+0x/N4J7oMNRQhFVYeVPZcDTDy9SBrs/91PkU/
# cGQgSWCKxST3epPFLQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFLPyOT4MNCQFYQ3W
# AdsjyCPJeLTsMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1Ud
# HwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggr
# BgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
# bS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIw
# MTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgw
# DgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQANnWTMm4VcUl02ycxY
# LzYjAlefwMp+VLsyVOPeWA7XHn6JXdHoUfUARgYR5gDLddFmAh89lkFMjN5kA+CL
# B3xC9SRMIBvbRqu9bnJ/XZJywRw99Cb20EYSCnLxUp70QgqVaYpTPBf2GllwvVYm
# 0nn/z1NhlgPtc7OuFRcSah3rsvCqq0MnxdtEgp3fM0WZeGGAXI4fRtBo4SR1DwGB
# MdK/I0lo8otqNlgBw+gqaQbZMJ2Un+wOvAy+DsMAaZhQd/r7m44DcGiAkvn5Blb0
# Zz9mYJpX52gGrPDMe4oCanIqqtEOgJ/tKx49ZMYrDXSIk8xZbuRsNnoV6S65efZL
# 7JjjVQCR4Z3acd5/9K++kx/t1jUvVE/Y28UJBPrdrYYn+jCuZKxTJ5ASAgkfw1XF
# dasPbIOrDBKNMFkl5UGF73EFgOuXlc0pKLMpYSJSGWSy9xh2Q9S0LQI6dgORewty
# MODbewu2gwn6RcaJt2bpUZxSaJZTx297p4/YQPcb0Yip1jADKUuDGQKIleDtvc1i
# mXVM8oKe4A+FoyitdeSgidKLxHH/dgJ8DAFzJzbNaNCwrM4Prg5okGbOXke483Ss
# 1Xxdc+23w2DTwCb5uaUkHW8t8CDrDf7LWIzPhJGj7VM6/DsjMKxvo6RTG7AeHHze
# rbyHhra7ZJTCRbZxevAnGWeSADCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkA
# AAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVow
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX
# 9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1q
# UoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8d
# q6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byN
# pOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2k
# rnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4d
# Pf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgS
# Uei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8
# QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6Cm
# gyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzF
# ER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQID
# AQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU
# KqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1
# GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0
# bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMA
# QTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbL
# j+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
# Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIz
# LmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwU
# tj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN
# 3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU
# 5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5
# KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGy
# qVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB6
# 2FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltE
# AY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFp
# AUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcd
# FYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRb
# atGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQd
# VTNYs6FwZvKhggLXMIICQAIBATCCAQChgdikgdUwgdIxCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5k
# IE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046ODZE
# Ri00QkJDLTkzMzUxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZp
# Y2WiIwoBATAHBgUrDgMCGgMVAMhnQRjDmzg5bBgWZklF9qFoH6nGoIGDMIGApH4w
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEFBQACBQDo
# a9f8MCIYDzIwMjMwNzI3MDEzNTU2WhgPMjAyMzA3MjgwMTM1NTZaMHcwPQYKKwYB
# BAGEWQoEATEvMC0wCgIFAOhr1/wCAQAwCgIBAAICBFECAf8wBwIBAAICEUkwCgIF
# AOhtKXwCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgCAQAC
# AwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUFAAOBgQBmKuccoVz9RZMwcRWY
# Tt3zxANudbfDllq1Xlffj8WLp+58CbCRaV1O+IBvBD1DPlyAWAZUAteD808keXV+
# Ac5Cal8ZnCkVx+zwr6B8xe7OGSckLC1YFjmXS2QvwlI4oETupgKjZX+6urnxl3cd
# DQWFZW5hisep65uoseyKBB3UxTGCBA0wggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
# LVN0YW1wIFBDQSAyMDEwAhMzAAABtyEnGgeiKoZGAAEAAAG3MA0GCWCGSAFlAwQC
# AQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZIhvcNAQkE
# MSIEILB2U26mTPHy6d3xwB/813BgsUS8gncAT5ozCkfzYCm4MIH6BgsqhkiG9w0B
# CRACLzGB6jCB5zCB5DCBvQQgbCd407Ie2i/ITXomBi+f/CAZ/M1H6+/0O65DPInN
# cEEwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
# MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
# MSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAbch
# JxoHoiqGRgABAAABtzAiBCBYpwWIxje7WHaGOkpq5RvMnG9IXr8x9uKlG8SIJhmT
# vTANBgkqhkiG9w0BAQsFAASCAgBC0CYsel+hSwXLSitBcse01gs5fAUI6FHj4QXu
# rEtAGhTYomGem3dD2vStbVDIKfMwKb8co30mVdYhw0aG19i6CXoxFi+g3C8RLrjt
# GBR+lo6rq8hqPx2ucho0rkhWbAos8v3MYuuv+FRXbuUdNHYLEDPIbHwirbhQUpFS
# 7FJTZNLoGh08+PIkindITrTED1Tn/PlwIO5q97iTpB2/uV/SN4Jv/vxFCi5GubDN
# KB/M0xyMhQ4CTVavmttEwT1cvvKMvM/lenKO6BrjyaEKB5Iimp1fPYvYa1GvEqP6
# ej5pf3TVn6Tspnj1GhKtGB/VUzd/WcXqPXTNsh9JvECES3CZj9EO+LZ5IG79aKGc
# WTKpGJrSjonQkCvhakfk7DIIO8ZSBFOoVI5jkPnGIHZt0rfZQExM7MkVPIf/nOJE
# +Uj+bxkrpagG33K7KCs9STwugWQoJuD9PNX8UYQThX+qCRsdt3Z6yoKloshEE8Ep
# uTKhpcXKiRxOP1gb0wq6kpa3AxxLXrdEtab0nYBioPJxxiGQxy1s/ULWpoKVh6Fg
# wB7ZUfeTHMc8yq7eyTy095xTPy12NP8zPxnFiyogBRD6yTa9K/3vl+V/VXpN0vCV
# QY86RUyA/CIlJPhXxRNXQ/HePSZeFWCufIzMo/N8FJKE5m5tPggHIgjJ32GJGqxY
# pgHx2A==
# SIG # End signature block
