#
# Module manifest for module 'Microsoft.Graph.Groups'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/26/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Groups.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '50bc9e18-e281-4208-8913-c9e1bef6083d'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.2.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Groups.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Groups.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgGroupDriveListContentTypeCopy', 
               'Add-MgGroupDriveListContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupFavorite', 'Add-MgGroupSite', 
               'Add-MgGroupSiteContentTypeCopy', 
               'Add-MgGroupSiteContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupSiteListContentTypeCopy', 
               'Add-MgGroupSiteListContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupToLifecyclePolicy', 
               'Confirm-MgGroupGrantedPermissionForApp', 
               'Confirm-MgGroupMemberGroup', 'Confirm-MgGroupMemberObject', 
               'Confirm-MgGroupPermissionGrantMemberGroup', 
               'Confirm-MgGroupPermissionGrantMemberObject', 
               'Confirm-MgGroupSettingTemplateMemberGroup', 
               'Confirm-MgGroupSettingTemplateMemberObject', 
               'Copy-MgGroupDriveItem', 
               'Copy-MgGroupDriveListContentTypeToDefaultContentLocation', 
               'Copy-MgGroupDriveRoot', 'Copy-MgGroupOnenoteNotebook', 
               'Copy-MgGroupOnenotePageToSection', 
               'Copy-MgGroupOnenoteSectionToNotebook', 
               'Copy-MgGroupOnenoteSectionToSectionGroup', 
               'Copy-MgGroupSiteContentTypeToDefaultContentLocation', 
               'Copy-MgGroupSiteListContentTypeToDefaultContentLocation', 
               'Get-MgAllGroupSite', 'Get-MgGroup', 'Get-MgGroupAcceptedSender', 
               'Get-MgGroupAcceptedSenderByRef', 'Get-MgGroupAcceptedSenderCount', 
               'Get-MgGroupById', 'Get-MgGroupCalendarEventDelta', 
               'Get-MgGroupCalendarSchedule', 'Get-MgGroupConversation', 
               'Get-MgGroupConversationCount', 'Get-MgGroupConversationThread', 
               'Get-MgGroupConversationThreadCount', 
               'Get-MgGroupConversationThreadPost', 
               'Get-MgGroupConversationThreadPostAttachment', 
               'Get-MgGroupConversationThreadPostAttachmentCount', 
               'Get-MgGroupConversationThreadPostCount', 
               'Get-MgGroupConversationThreadPostExtension', 
               'Get-MgGroupConversationThreadPostExtensionCount', 
               'Get-MgGroupConversationThreadPostInReplyToAttachment', 
               'Get-MgGroupConversationThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupConversationThreadPostInReplyToExtension', 
               'Get-MgGroupConversationThreadPostInReplyToExtensionCount', 
               'Get-MgGroupCount', 'Get-MgGroupCreatedOnBehalfOf', 
               'Get-MgGroupDelta', 'Get-MgGroupDriveItemActivityByInterval', 
               'Get-MgGroupDriveItemDelta', 
               'Get-MgGroupDriveItemListItemActivityByInterval', 
               'Get-MgGroupDriveListContentTypeCompatibleHubContentType', 
               'Get-MgGroupDriveListItemActivityByInterval', 
               'Get-MgGroupDriveRootActivityByInterval', 
               'Get-MgGroupDriveRootDelta', 
               'Get-MgGroupDriveRootListItemActivityByInterval', 
               'Get-MgGroupEventDelta', 'Get-MgGroupExtension', 
               'Get-MgGroupExtensionCount', 'Get-MgGroupLifecyclePolicy', 
               'Get-MgGroupLifecyclePolicyByGroup', 
               'Get-MgGroupLifecyclePolicyCount', 'Get-MgGroupMember', 
               'Get-MgGroupMemberAsApplication', 'Get-MgGroupMemberAsDevice', 
               'Get-MgGroupMemberAsGroup', 'Get-MgGroupMemberAsOrgContact', 
               'Get-MgGroupMemberAsServicePrincipal', 'Get-MgGroupMemberAsUser', 
               'Get-MgGroupMemberByRef', 'Get-MgGroupMemberCount', 
               'Get-MgGroupMemberCountAsApplication', 
               'Get-MgGroupMemberCountAsDevice', 'Get-MgGroupMemberCountAsGroup', 
               'Get-MgGroupMemberCountAsOrgContact', 
               'Get-MgGroupMemberCountAsServicePrincipal', 
               'Get-MgGroupMemberCountAsUser', 'Get-MgGroupMemberGroup', 
               'Get-MgGroupMemberObject', 'Get-MgGroupMemberOf', 
               'Get-MgGroupMemberOfAsAdministrativeUnit', 
               'Get-MgGroupMemberOfAsGroup', 'Get-MgGroupMemberOfCount', 
               'Get-MgGroupMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupMemberOfCountAsGroup', 
               'Get-MgGroupMemberWithLicenseError', 
               'Get-MgGroupMemberWithLicenseErrorAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorAsUser', 
               'Get-MgGroupMemberWithLicenseErrorCount', 
               'Get-MgGroupMemberWithLicenseErrorCountAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorCountAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorCountAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorCountAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorCountAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorCountAsUser', 
               'Get-MgGroupOnenoteNotebookFromWebUrl', 
               'Get-MgGroupOnenoteRecentNotebook', 'Get-MgGroupOwner', 
               'Get-MgGroupOwnerAsApplication', 'Get-MgGroupOwnerAsDevice', 
               'Get-MgGroupOwnerAsGroup', 'Get-MgGroupOwnerAsOrgContact', 
               'Get-MgGroupOwnerAsServicePrincipal', 'Get-MgGroupOwnerAsUser', 
               'Get-MgGroupOwnerByRef', 'Get-MgGroupOwnerCount', 
               'Get-MgGroupOwnerCountAsApplication', 
               'Get-MgGroupOwnerCountAsDevice', 'Get-MgGroupOwnerCountAsGroup', 
               'Get-MgGroupOwnerCountAsOrgContact', 
               'Get-MgGroupOwnerCountAsServicePrincipal', 
               'Get-MgGroupOwnerCountAsUser', 'Get-MgGroupPermissionGrant', 
               'Get-MgGroupPermissionGrantById', 'Get-MgGroupPermissionGrantCount', 
               'Get-MgGroupPermissionGrantDelta', 
               'Get-MgGroupPermissionGrantMemberGroup', 
               'Get-MgGroupPermissionGrantMemberObject', 'Get-MgGroupPhoto', 
               'Get-MgGroupPhotoContent', 'Get-MgGroupPhotoCount', 
               'Get-MgGroupRejectedSender', 'Get-MgGroupRejectedSenderByRef', 
               'Get-MgGroupRejectedSenderCount', 'Get-MgGroupSetting', 
               'Get-MgGroupSettingCount', 'Get-MgGroupSettingTemplateById', 
               'Get-MgGroupSettingTemplateCount', 
               'Get-MgGroupSettingTemplateDelta', 
               'Get-MgGroupSettingTemplateGroupSettingTemplate', 
               'Get-MgGroupSettingTemplateMemberGroup', 
               'Get-MgGroupSettingTemplateMemberObject', 
               'Get-MgGroupSiteActivityByInterval', 
               'Get-MgGroupSiteApplicableContentTypeForList', 
               'Get-MgGroupSiteByPath', 
               'Get-MgGroupSiteContentTypeCompatibleHubContentType', 
               'Get-MgGroupSiteListContentTypeCompatibleHubContentType', 
               'Get-MgGroupSiteListItemActivityByInterval', 'Get-MgGroupThread', 
               'Get-MgGroupThreadCount', 'Get-MgGroupThreadPost', 
               'Get-MgGroupThreadPostAttachment', 
               'Get-MgGroupThreadPostAttachmentCount', 
               'Get-MgGroupThreadPostCount', 'Get-MgGroupThreadPostExtension', 
               'Get-MgGroupThreadPostExtensionCount', 
               'Get-MgGroupThreadPostInReplyToAttachment', 
               'Get-MgGroupThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupThreadPostInReplyToExtension', 
               'Get-MgGroupThreadPostInReplyToExtensionCount', 
               'Get-MgGroupTransitiveMember', 
               'Get-MgGroupTransitiveMemberAsApplication', 
               'Get-MgGroupTransitiveMemberAsDevice', 
               'Get-MgGroupTransitiveMemberAsGroup', 
               'Get-MgGroupTransitiveMemberAsOrgContact', 
               'Get-MgGroupTransitiveMemberAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberAsUser', 
               'Get-MgGroupTransitiveMemberCount', 
               'Get-MgGroupTransitiveMemberCountAsApplication', 
               'Get-MgGroupTransitiveMemberCountAsDevice', 
               'Get-MgGroupTransitiveMemberCountAsGroup', 
               'Get-MgGroupTransitiveMemberCountAsOrgContact', 
               'Get-MgGroupTransitiveMemberCountAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberCountAsUser', 
               'Get-MgGroupTransitiveMemberOf', 
               'Get-MgGroupTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfAsGroup', 
               'Get-MgGroupTransitiveMemberOfCount', 
               'Get-MgGroupTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfCountAsGroup', 
               'Grant-MgGroupDriveItemPermission', 
               'Grant-MgGroupDriveRootPermission', 'Grant-MgGroupSitePermission', 
               'Invoke-MgAcceptGroupCalendarEvent', 
               'Invoke-MgAcceptGroupCalendarEventTentatively', 
               'Invoke-MgAcceptGroupEvent', 'Invoke-MgAcceptGroupEventTentatively', 
               'Invoke-MgCalendarGroupCalendar', 'Invoke-MgCheckinGroupDriveItem', 
               'Invoke-MgCheckinGroupDriveRoot', 'Invoke-MgCheckoutGroupDriveItem', 
               'Invoke-MgCheckoutGroupDriveRoot', 
               'Invoke-MgDeclineGroupCalendarEvent', 'Invoke-MgDeclineGroupEvent', 
               'Invoke-MgDismissGroupCalendarEventReminder', 
               'Invoke-MgDismissGroupEventReminder', 
               'Invoke-MgExtractGroupDriveItemSensitivityLabel', 
               'Invoke-MgExtractGroupDriveRootSensitivityLabel', 
               'Invoke-MgFollowGroupDriveItem', 'Invoke-MgFollowGroupDriveRoot', 
               'Invoke-MgForwardGroupCalendarEvent', 
               'Invoke-MgForwardGroupConversationThreadPost', 
               'Invoke-MgForwardGroupConversationThreadPostInReplyTo', 
               'Invoke-MgForwardGroupEvent', 'Invoke-MgForwardGroupThreadPost', 
               'Invoke-MgForwardGroupThreadPostInReplyTo', 'Invoke-MgGraphGroup', 
               'Invoke-MgGraphGroupDrive', 'Invoke-MgInviteGroupDriveItem', 
               'Invoke-MgInviteGroupDriveRoot', 'Invoke-MgPreviewGroupDriveItem', 
               'Invoke-MgPreviewGroupDriveRoot', 
               'Invoke-MgPreviewGroupOnenotePage', 
               'Invoke-MgReauthorizeGroupDriveItemSubscription', 
               'Invoke-MgReauthorizeGroupDriveListSubscription', 
               'Invoke-MgReauthorizeGroupDriveRootSubscription', 
               'Invoke-MgReauthorizeGroupSiteListSubscription', 
               'Invoke-MgRecentGroupDrive', 'Invoke-MgRenewGroup', 
               'Invoke-MgReplyGroupConversationThread', 
               'Invoke-MgReplyGroupConversationThreadPost', 
               'Invoke-MgReplyGroupConversationThreadPostInReplyTo', 
               'Invoke-MgReplyGroupThread', 'Invoke-MgReplyGroupThreadPost', 
               'Invoke-MgReplyGroupThreadPostInReplyTo', 
               'Invoke-MgSnoozeGroupCalendarEventReminder', 
               'Invoke-MgSnoozeGroupEventReminder', 
               'Invoke-MgSubscribeGroupByMail', 'Invoke-MgUnfollowGroupDriveItem', 
               'Invoke-MgUnfollowGroupDriveRoot', 
               'Join-MgGroupDriveListContentTypeWithHubSite', 
               'Join-MgGroupSiteContentTypeWithHubSite', 
               'Join-MgGroupSiteListContentTypeWithHubSite', 'New-MgGroup', 
               'New-MgGroupAcceptedSenderByRef', 'New-MgGroupConversation', 
               'New-MgGroupConversationThread', 
               'New-MgGroupConversationThreadPostAttachment', 
               'New-MgGroupConversationThreadPostAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostExtension', 
               'New-MgGroupConversationThreadPostInReplyToAttachment', 
               'New-MgGroupConversationThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostInReplyToExtension', 
               'New-MgGroupDriveItemLink', 'New-MgGroupDriveItemUploadSession', 
               'New-MgGroupDriveRootLink', 'New-MgGroupDriveRootUploadSession', 
               'New-MgGroupExtension', 'New-MgGroupLifecyclePolicy', 
               'New-MgGroupMember', 'New-MgGroupMemberByRef', 'New-MgGroupOwner', 
               'New-MgGroupOwnerByRef', 'New-MgGroupPermissionGrant', 
               'New-MgGroupRejectedSenderByRef', 'New-MgGroupSetting', 
               'New-MgGroupSettingTemplateGroupSettingTemplate', 
               'New-MgGroupThread', 'New-MgGroupThreadPostAttachment', 
               'New-MgGroupThreadPostAttachmentUploadSession', 
               'New-MgGroupThreadPostExtension', 
               'New-MgGroupThreadPostInReplyToAttachment', 
               'New-MgGroupThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupThreadPostInReplyToExtension', 
               'Publish-MgGroupDriveListContentType', 
               'Publish-MgGroupSiteContentType', 
               'Publish-MgGroupSiteListContentType', 'Remove-MgGroup', 
               'Remove-MgGroupAcceptedSenderByRef', 'Remove-MgGroupConversation', 
               'Remove-MgGroupConversationThread', 
               'Remove-MgGroupConversationThreadPostAttachment', 
               'Remove-MgGroupConversationThreadPostExtension', 
               'Remove-MgGroupConversationThreadPostInReplyToAttachment', 
               'Remove-MgGroupConversationThreadPostInReplyToExtension', 
               'Remove-MgGroupDriveItemPermanent', 
               'Remove-MgGroupDriveRootPermanent', 'Remove-MgGroupExtension', 
               'Remove-MgGroupFavorite', 'Remove-MgGroupFromLifecyclePolicy', 
               'Remove-MgGroupLifecyclePolicy', 'Remove-MgGroupMemberByRef', 
               'Remove-MgGroupOwnerByRef', 'Remove-MgGroupPermissionGrant', 
               'Remove-MgGroupPhoto', 'Remove-MgGroupRejectedSenderByRef', 
               'Remove-MgGroupSetting', 
               'Remove-MgGroupSettingTemplateGroupSettingTemplate', 
               'Remove-MgGroupSite', 'Remove-MgGroupThread', 
               'Remove-MgGroupThreadPostAttachment', 
               'Remove-MgGroupThreadPostExtension', 
               'Remove-MgGroupThreadPostInReplyToAttachment', 
               'Remove-MgGroupThreadPostInReplyToExtension', 
               'Reset-MgGroupUnseenCount', 'Restore-MgGroupDriveItem', 
               'Restore-MgGroupDriveItemListItemDocumentSetVersion', 
               'Restore-MgGroupDriveItemListItemVersion', 
               'Restore-MgGroupDriveItemVersion', 
               'Restore-MgGroupDriveListItemDocumentSetVersion', 
               'Restore-MgGroupDriveListItemVersion', 'Restore-MgGroupDriveRoot', 
               'Restore-MgGroupDriveRootListItemDocumentSetVersion', 
               'Restore-MgGroupDriveRootListItemVersion', 
               'Restore-MgGroupDriveRootVersion', 'Restore-MgGroupSettingTemplate', 
               'Restore-MgGroupSiteListItemDocumentSetVersion', 
               'Restore-MgGroupSiteListItemVersion', 'Search-MgGroupDrive', 
               'Search-MgGroupDriveItem', 'Search-MgGroupDriveRoot', 
               'Set-MgGroupDriveItemSensitivityLabel', 
               'Set-MgGroupDriveRootSensitivityLabel', 'Set-MgGroupLicense', 
               'Set-MgGroupPhotoContent', 'Stop-MgGroupCalendarEvent', 
               'Stop-MgGroupEvent', 'Test-MgGroupDriveItemPermission', 
               'Test-MgGroupDriveListContentTypePublished', 
               'Test-MgGroupDriveRootPermission', 
               'Test-MgGroupPermissionGrantProperty', 'Test-MgGroupProperty', 
               'Test-MgGroupSettingTemplateProperty', 
               'Test-MgGroupSiteContentTypePublished', 
               'Test-MgGroupSiteListContentTypePublished', 
               'Unpublish-MgGroupDriveListContentType', 
               'Unpublish-MgGroupSiteContentType', 
               'Unpublish-MgGroupSiteListContentType', 'Update-MgGroup', 
               'Update-MgGroupConversationThread', 
               'Update-MgGroupConversationThreadPostExtension', 
               'Update-MgGroupConversationThreadPostInReplyToExtension', 
               'Update-MgGroupExtension', 'Update-MgGroupLifecyclePolicy', 
               'Update-MgGroupOnenotePageContent', 'Update-MgGroupPermissionGrant', 
               'Update-MgGroupPhoto', 'Update-MgGroupSetting', 
               'Update-MgGroupSettingTemplateGroupSettingTemplate', 
               'Update-MgGroupThread', 'Update-MgGroupThreadPostExtension', 
               'Update-MgGroupThreadPostInReplyToExtension'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInlgYJKoZIhvcNAQcCoIInhzCCJ4MCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCJhDcikhfdI3xi
# bHIBdc1qRF9cwu0zr0oYmLVydI2ilaCCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGXYwghlyAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEICU///gYslyPDBC7sqdTm89Q
# NTVt15B9h1cOEWyG77w3MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEALp7tNJxoCx91QbMV+phVw094Pk6cuodUqRREMznzPBIT/7uO2xXbE5TU
# sPJNuzdFbY9PqNluzLqjDGUHW/0YWGwsmrodZ9MD6D2QfqhDrymw16RqjrSFPN1g
# cUApczjnlCucA+OdS1/SrbKqomGMfmcAyqqomJE1sxXZn3wyQu2xjrouB0lDvf9h
# /10CacdsUx5gmwDKH87ck0TBauR0MbQeP1v3m/2WT7quDKCwlfbEP1ck5Jz56EQS
# 42lMa8rTJdfJXwnXuH/mN15rdgz8hb4jWI8R7VEte8S2NaTgAOF2nShqyU5byRnK
# i7NJEGwBTRZe+uSs2ytSWitU12LYWKGCFwAwghb8BgorBgEEAYI3AwMBMYIW7DCC
# FugGCSqGSIb3DQEHAqCCFtkwghbVAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFRBgsq
# hkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCC4Z8eA4qvkyL4pwC7VEepGPQHwH2+iTY5934e0EMhKxwIGZLAQ91s+
# GBMyMDIzMDcyNjE5MTg1OS42MzdaMASAAgH0oIHQpIHNMIHKMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjozRTdBLUUz
# NTktQTI1RDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
# EVcwggcMMIIE9KADAgECAhMzAAAByfrVjiUgdAJeAAEAAAHJMA0GCSqGSIb3DQEB
# CwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIyMTEwNDE5MDEz
# OFoXDTI0MDIwMjE5MDEzOFowgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMx
# JjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOjNFN0EtRTM1OS1BMjVEMSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEF
# AAOCAg8AMIICCgKCAgEA1nLi5Y5vz8K+Woxhk7qGW/vCxi5euTM01TiEbFOG8g7S
# FB0VMjYgo6TiRzgOQ+CN53OBOKlyMHWzRL4xvaS03ZlIgetIILYiASogsEtljzEl
# RHO7fDGDFWcdz+lCNYmJoztbG3PMrnxblUHHUkr4C7EBHb2Y07Gd5GJBgP8+5AZN
# sTlsHGczHs45mmP7rUgcMn//c8Q/GYSqdT4OXELp53h99EnyF4zcsd2ZFjxdj1lP
# 8QGwZZS4F82JBGe2pCrSakyFjTxzFKUOwcQerwBR/YaQly7mtCra4PNcyEQm+n/L
# Dce/VViQa8OM2nBZHKw6CyMqEzFJJy5Hizz8Z6xrqqLKti8viJUQ0FtqkTXSR3//
# w8PAKyBlvIYTFF/Ly3Jh3cbVeOgSmubOVwv8nMehcQb2AtxcU/ldyEUqy8/thEHI
# WNabzHXx5O9D4btS6oJdgLmHxrTBtGscVQqx0z5/fUIkLE7tbwfoq84cF/URLEyw
# 3q57KV2U4gOhc356XYEVQdJXo6VFWBQDYbzanQ25zY21UCkj821CyD90gqrO3rQP
# lcQo6erwW2DF2fsmgAbVqzQsz6Rkmafz4re17km7qe09PuwHw5e3x5ZIGEoVlfNn
# Jv6+851uwKX6ApZFxPzeQo7W/5BtaTmkZEhwY5AdCPgPv0aaIEQn2qF7MvFwCcsC
# AwEAAaOCATYwggEyMB0GA1UdDgQWBBQFb51nRsI8ob54OhTFeVF7RC4yyzAfBgNV
# HSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5o
# dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
# aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
# CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRz
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IC
# AQA2qLqcZt9HikIHcj7AlnHhjouxSjOeBaTE+EK8aXcVLm9cA8D2/ZY2OUpYvOdh
# uDEV9hElVmzopiJuk/xBYh6dWJTRhmS7hVjrGtqzSFW0LffsRysjxkpuqyhHiBDx
# MXMGZ6GdzUfqVP2Zd2O+J/BYQJgs9NHYz/CM4XaRP+T2VM3JE1mSO1qLa+mfB427
# QiLj/JC7TUYgh4RY+oLMFVuQJZvXYl/jITFfUppJoAakBr0Vc2r1kP5DiJaNvZWJ
# /cuYaiWQ4k9xpw6wGz3qq7xAWnlGzsawwFhjtwq5EH/s37LCfehyuCw8ZRJ9W3tg
# SFepAVM7sUE+Pr3Uu+iPvBV4TsTDNFL0CVIPX+1XOJ6YRGYJ2kHGpoGc/5sgA2IK
# Qcl97ZDYJIqixgwKNftyN70O0ATbpTVhsbN01FVli0H+vgcGhyzk6jpAywHPDSQ/
# xoEeGU4+6PFTXMRO/fMzGcUcf0ZHqZMm0UhoH8tOtk18k6B75KJXTtY3ZM7pTfur
# Sv2Qrv5zzCBiyystOPw/IJI+k9opTgatrC39L69/KwytD0x7t0jmTXtlLZaGvoSl
# jdyyr6QDRVkqsCaLUSSsAiWeav5qg64U3mLmeeko0E9TJ5yztN/jcizlHx0XsgOu
# N6sub3CPV7AAMMiKopdQYqiPXu9IxvqXT7CE/SMC2pcNyTCCB3EwggVZoAMCAQIC
# EzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoX
# DTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC
# 0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VG
# Iwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP
# 2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/P
# XfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361
# VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwB
# Sru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9
# X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269e
# wvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDw
# wvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr
# 9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+e
# FnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAj
# BgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+n
# FV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEw
# PwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9j
# cy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3
# FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAf
# BgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBH
# hkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUF
# BzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0Nl
# ckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4Swf
# ZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTC
# j/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu
# 2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/
# GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3D
# YXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbO
# xnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqO
# Cb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I
# 6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0
# zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaM
# mdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNT
# TY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLOMIICNwIBATCB+KGB0KSBzTCByjEL
# MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
# bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWlj
# cm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEmMCQGA1UECxMdVGhhbGVzIFRTUyBF
# U046M0U3QS1FMzU5LUEyNUQxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAH3pi8v+HgGbjVQs4G36dRxWBt0OoIGD
# MIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQG
# A1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEF
# BQACBQDoa7JpMCIYDzIwMjMwNzI2MjI1NTM3WhgPMjAyMzA3MjcyMjU1MzdaMHcw
# PQYKKwYBBAGEWQoEATEvMC0wCgIFAOhrsmkCAQAwCgIBAAICEAYCAf8wBwIBAAIC
# ESswCgIFAOhtA+kCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAK
# MAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUFAAOBgQCFOqZ5beN1
# HH/DO1X4MzRQLicv7T8foqBZieHH6FSpZ8AvNOmXF0xXhJX2b1mN0LnrK0kGH6D3
# Oo/qV6Z5020jPQAtRj8PYgiQ+psuvM1a/EJYRd/FAgjd9obv2gjjGiHZtG7dhvuY
# txTKmA9j/R56lo5UUKe9C77Gf+tYx1fkbjGCBA0wggQJAgEBMIGTMHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAByfrVjiUgdAJeAAEAAAHJMA0GCWCG
# SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZI
# hvcNAQkEMSIEIB/BX+kDquVcIr6z8wFxuQtnv41s/d+2Y9qXhbHbH24NMIH6Bgsq
# hkiG9w0BCRACLzGB6jCB5zCB5DCBvQQggXXOf1LdUUsQJ3gp2H9gDSMhiQD/zX3h
# XXzh2Tl2/YEwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAIT
# MwAAAcn61Y4lIHQCXgABAAAByTAiBCCkQ3y4ek3d2w8LP/y0VYhrDP2zYP5nuDDu
# 3FHy45BUczANBgkqhkiG9w0BAQsFAASCAgAMk4KDL74GhMnzVsjg75i6G+Lywze+
# en9TJlN0s/L1xBoDgwPSwRhLzd9Ki5U+t0RxQIWwyCvVYMzT9Vd4fs1NmCbpwNHD
# iOZsD0dZndjDQVMrlasqGBcErLs+uX+E2QcDGPfaVbDW2OlJuQDyJZlLR8kaM7xe
# ignNsQI9+Gbq6RU3kLHMr5sv0wP34Gj/jvBOPLKizoUJ9bjZQcPDH7InApyFyBIY
# 9lBMxaOfXHL/ZzsbNK+vkiskQe7YbMedKo9CfTQXW3fs275LiEeGk/rA1SNxElwK
# QpqGHc6H511pS+EdFG1XXaysFgpRZu41gEVr2qFxyU0zB/jKs+qrxyCG2nrTL/+3
# UVoy2pXo3vgv4kDZTtF5L9RnUHuoOjPFRVxHmIH3538gjb+qDP5JnllLqqZMqsr3
# yuCnmF7X4Qn6cEIDxBebbwXtATd/1CehUOMTu4Il4i7oG3HsjhbgNmCdlOVFfllR
# X979kaVq1FTIHeehz5b8h7n1bEYGgG3XcZ8nbQOj9rahsai+WjYcstUqtAbgibAk
# Objxtw7BHKcdruWoRotoNNUajJiKH0b3WVvfrl7XAVu9dACttZZffBOc+bwoKdUO
# oHNU3ThbUzMQJ+knhNfwKnEuy1hLHLkd0MDn7oLnZgOYwuhN1Irudn7dffx2Ruoi
# RPtKo1trUSJHpQ==
# SIG # End signature block
