#
# Module manifest for module 'Microsoft.Graph.Devices.CorporateManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/26/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Devices.CorporateManagement.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '39dbb3bc-1a84-424a-9efe-683be70a1810'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.2.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Devices.CorporateManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Devices.CorporateManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgDeviceAppManagement', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionAssignmentCount', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementiOSManagedAppProtection', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionAppCount', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionAssignmentCount', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionCount', 
               'Get-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppManagementManagedAppPolicy', 
               'Get-MgDeviceAppManagementManagedAppPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistration', 
               'Get-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Get-MgDeviceAppManagementManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Get-MgDeviceAppManagementManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Get-MgDeviceAppManagementManagedAppRegistrationOperationCount', 
               'Get-MgDeviceAppManagementManagedAppRegistrationUserIdWithFlaggedAppRegistration', 
               'Get-MgDeviceAppManagementManagedAppStatus', 
               'Get-MgDeviceAppManagementManagedAppStatusCount', 
               'Get-MgDeviceAppManagementManagedEBook', 
               'Get-MgDeviceAppManagementManagedEBookAssignment', 
               'Get-MgDeviceAppManagementManagedEBookAssignmentCount', 
               'Get-MgDeviceAppManagementManagedEBookCount', 
               'Get-MgDeviceAppManagementManagedEBookDeviceState', 
               'Get-MgDeviceAppManagementManagedEBookDeviceStateCount', 
               'Get-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryCount', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Get-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignmentCount', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyCount', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgDeviceAppManagementMobileApp', 
               'Get-MgDeviceAppManagementMobileAppAsManagedMobileLobApp', 
               'Get-MgDeviceAppManagementMobileAppAsMobileLobApp', 
               'Get-MgDeviceAppManagementMobileAppAssignment', 
               'Get-MgDeviceAppManagementMobileAppAssignmentCount', 
               'Get-MgDeviceAppManagementMobileAppCategory', 
               'Get-MgDeviceAppManagementMobileAppCategoryCount', 
               'Get-MgDeviceAppManagementMobileAppConfiguration', 
               'Get-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Get-MgDeviceAppManagementMobileAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatusCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatusCount', 
               'Get-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Get-MgDeviceAppManagementMobileAppCount', 
               'Get-MgDeviceAppManagementMobileAppCountAsManagedMobileLobApp', 
               'Get-MgDeviceAppManagementMobileAppCountAsMobileLobApp', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAppCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationCount', 
               'Get-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgDeviceAppManagementVppToken', 
               'Get-MgDeviceAppManagementVppTokenCount', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyAssignmentCount', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyCount', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgUserDeviceManagementTroubleshootingEvent', 
               'Get-MgUserDeviceManagementTroubleshootingEventCount', 
               'Get-MgUserManagedAppRegistration', 
               'Get-MgUserManagedAppRegistrationCount', 'Get-MgUserManagedDevice', 
               'Get-MgUserManagedDeviceCategory', 
               'Get-MgUserManagedDeviceCompliancePolicyState', 
               'Get-MgUserManagedDeviceCompliancePolicyStateCount', 
               'Get-MgUserManagedDeviceConfigurationState', 
               'Get-MgUserManagedDeviceConfigurationStateCount', 
               'Get-MgUserManagedDeviceCount', 
               'Get-MgUserManagedDeviceLogCollectionRequestCount', 
               'Get-MgUserManagedDeviceLogCollectionResponse', 
               'Get-MgUserManagedDeviceUser', 
               'Get-MgUserManagedDeviceWindowsProtectionState', 
               'Get-MgUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgUserManagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Invoke-MgTargetDeviceAppManagementManagedAppPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementManagedAppRegistrationAppliedPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementManagedAppRegistrationIntendedPolicyApp', 
               'Invoke-MgTargetDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppManagementAndroidManagedAppProtection', 
               'New-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'New-MgDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'New-MgDeviceAppManagementDefaultManagedAppProtection', 
               'New-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'New-MgDeviceAppManagementiOSManagedAppProtection', 
               'New-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'New-MgDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'New-MgDeviceAppManagementManagedAppPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistration', 
               'New-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'New-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'New-MgDeviceAppManagementManagedAppStatus', 
               'New-MgDeviceAppManagementManagedEBook', 
               'New-MgDeviceAppManagementManagedEBookAssignment', 
               'New-MgDeviceAppManagementManagedEBookDeviceState', 
               'New-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'New-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'New-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'New-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'New-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgDeviceAppManagementMobileApp', 
               'New-MgDeviceAppManagementMobileAppAssignment', 
               'New-MgDeviceAppManagementMobileAppCategory', 
               'New-MgDeviceAppManagementMobileAppConfiguration', 
               'New-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'New-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'New-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'New-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'New-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'New-MgDeviceAppManagementVppToken', 
               'New-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'New-MgDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'New-MgDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgUserDeviceManagementTroubleshootingEvent', 
               'New-MgUserManagedDevice', 
               'New-MgUserManagedDeviceCompliancePolicyState', 
               'New-MgUserManagedDeviceConfigurationState', 
               'New-MgUserManagedDeviceLogCollectionResponse', 
               'New-MgUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Remove-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtection', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Remove-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppManagementManagedAppPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistration', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Remove-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Remove-MgDeviceAppManagementManagedAppStatus', 
               'Remove-MgDeviceAppManagementManagedEBook', 
               'Remove-MgDeviceAppManagementManagedEBookAssignment', 
               'Remove-MgDeviceAppManagementManagedEBookDeviceState', 
               'Remove-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Remove-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Remove-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Remove-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Remove-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgDeviceAppManagementMobileApp', 
               'Remove-MgDeviceAppManagementMobileAppAssignment', 
               'Remove-MgDeviceAppManagementMobileAppCategory', 
               'Remove-MgDeviceAppManagementMobileAppConfiguration', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Remove-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Remove-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgDeviceAppManagementVppToken', 
               'Remove-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Remove-MgDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Remove-MgDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgUserDeviceManagementTroubleshootingEvent', 
               'Remove-MgUserManagedDevice', 'Remove-MgUserManagedDeviceCategory', 
               'Remove-MgUserManagedDeviceCompliancePolicyState', 
               'Remove-MgUserManagedDeviceConfigurationState', 
               'Remove-MgUserManagedDeviceLogCollectionResponse', 
               'Remove-MgUserManagedDeviceWindowsProtectionState', 
               'Remove-MgUserManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Set-MgDeviceAppManagementManagedEBook', 
               'Set-MgDeviceAppManagementMobileApp', 
               'Set-MgDeviceAppManagementMobileAppConfiguration', 
               'Set-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Sync-MgDeviceAppManagementMicrosoftStoreForBusinessApp', 
               'Sync-MgDeviceAppManagementVppTokenLicense', 
               'Update-MgDeviceAppManagement', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtection', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtectionAssignment', 
               'Update-MgDeviceAppManagementAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtection', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementiOSManagedAppProtection', 
               'Update-MgDeviceAppManagementiOSManagedAppProtectionApp', 
               'Update-MgDeviceAppManagementiOSManagedAppProtectionAssignment', 
               'Update-MgDeviceAppManagementiOSManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppManagementManagedAppPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistration', 
               'Update-MgDeviceAppManagementManagedAppRegistrationAppliedPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistrationIntendedPolicy', 
               'Update-MgDeviceAppManagementManagedAppRegistrationOperation', 
               'Update-MgDeviceAppManagementManagedAppStatus', 
               'Update-MgDeviceAppManagementManagedEBook', 
               'Update-MgDeviceAppManagementManagedEBookAssignment', 
               'Update-MgDeviceAppManagementManagedEBookDeviceState', 
               'Update-MgDeviceAppManagementManagedEBookInstallSummary', 
               'Update-MgDeviceAppManagementManagedEBookUserStateSummary', 
               'Update-MgDeviceAppManagementManagedEBookUserStateSummaryDeviceState', 
               'Update-MgDeviceAppManagementMdmWindowsInformationProtectionPolicy', 
               'Update-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyAssignment', 
               'Update-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgDeviceAppManagementMdmWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgDeviceAppManagementMobileApp', 
               'Update-MgDeviceAppManagementMobileAppAssignment', 
               'Update-MgDeviceAppManagementMobileAppCategory', 
               'Update-MgDeviceAppManagementMobileAppConfiguration', 
               'Update-MgDeviceAppManagementMobileAppConfigurationAssignment', 
               'Update-MgDeviceAppManagementMobileAppConfigurationDeviceStatus', 
               'Update-MgDeviceAppManagementMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgDeviceAppManagementMobileAppConfigurationUserStatus', 
               'Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfiguration', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationApp', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationAssignment', 
               'Update-MgDeviceAppManagementTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgDeviceAppManagementVppToken', 
               'Update-MgDeviceAppManagementWindowsInformationProtectionPolicy', 
               'Update-MgDeviceAppManagementWindowsInformationProtectionPolicyAssignment', 
               'Update-MgDeviceAppManagementWindowsInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgDeviceAppManagementWindowsInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgUserDeviceManagementTroubleshootingEvent', 
               'Update-MgUserManagedDevice', 'Update-MgUserManagedDeviceCategory', 
               'Update-MgUserManagedDeviceCompliancePolicyState', 
               'Update-MgUserManagedDeviceConfigurationState', 
               'Update-MgUserManagedDeviceLogCollectionResponse', 
               'Update-MgUserManagedDeviceWindowsProtectionState', 
               'Update-MgUserManagedDeviceWindowsProtectionStateDetectedMalwareState'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgDeviceAppMgt', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionAssignmentCount', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtiOSManagedAppProtection', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionApp', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionAppCount', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionAssignmentCount', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionCount', 
               'Get-MgDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Get-MgDeviceAppMgtManagedAppPolicy', 
               'Get-MgDeviceAppMgtManagedAppPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistration', 
               'Get-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Get-MgDeviceAppMgtManagedAppRegistrationAppliedPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Get-MgDeviceAppMgtManagedAppRegistrationIntendedPolicyCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Get-MgDeviceAppMgtManagedAppRegistrationOperationCount', 
               'Get-MgDeviceAppMgtManagedAppRegistrationUserIdGraphWPreFlaggedAppRegistration', 
               'Get-MgDeviceAppMgtManagedAppStatus', 
               'Get-MgDeviceAppMgtManagedAppStatusCount', 
               'Get-MgDeviceAppMgtManagedEBook', 
               'Get-MgDeviceAppMgtManagedEBookAssignment', 
               'Get-MgDeviceAppMgtManagedEBookAssignmentCount', 
               'Get-MgDeviceAppMgtManagedEBookCount', 
               'Get-MgDeviceAppMgtManagedEBookDeviceState', 
               'Get-MgDeviceAppMgtManagedEBookDeviceStateCount', 
               'Get-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryCount', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Get-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceStateCount', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyAssignmentCount', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyCount', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFileCount', 
               'Get-MgDeviceAppMgtMobileApp', 
               'Get-MgDeviceAppMgtMobileAppAsManagedMobileLobApp', 
               'Get-MgDeviceAppMgtMobileAppAsMobileLobApp', 
               'Get-MgDeviceAppMgtMobileAppAssignment', 
               'Get-MgDeviceAppMgtMobileAppAssignmentCount', 
               'Get-MgDeviceAppMgtMobileAppCategory', 
               'Get-MgDeviceAppMgtMobileAppCategoryCount', 
               'Get-MgDeviceAppMgtMobileAppConfiguration', 
               'Get-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Get-MgDeviceAppMgtMobileAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatusCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatusCount', 
               'Get-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Get-MgDeviceAppMgtMobileAppCount', 
               'Get-MgDeviceAppMgtMobileAppCountAsManagedMobileLobApp', 
               'Get-MgDeviceAppMgtMobileAppCountAsMobileLobApp', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAppCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignmentCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationCount', 
               'Get-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Get-MgDeviceAppMgtVppToken', 'Get-MgDeviceAppMgtVppTokenCount', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyAssignmentCount', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyCount', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFileCount', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Get-MgDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFileCount', 
               'New-MgDeviceAppMgtAndroidManagedAppProtection', 
               'New-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'New-MgDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'New-MgDeviceAppMgtDefaultManagedAppProtection', 
               'New-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'New-MgDeviceAppMgtiOSManagedAppProtection', 
               'New-MgDeviceAppMgtiOSManagedAppProtectionApp', 
               'New-MgDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'New-MgDeviceAppMgtManagedAppPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistration', 
               'New-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'New-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'New-MgDeviceAppMgtManagedAppStatus', 
               'New-MgDeviceAppMgtManagedEBook', 
               'New-MgDeviceAppMgtManagedEBookAssignment', 
               'New-MgDeviceAppMgtManagedEBookDeviceState', 
               'New-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'New-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'New-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'New-MgDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'New-MgDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'New-MgDeviceAppMgtMobileApp', 
               'New-MgDeviceAppMgtMobileAppAssignment', 
               'New-MgDeviceAppMgtMobileAppCategory', 
               'New-MgDeviceAppMgtMobileAppConfiguration', 
               'New-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'New-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'New-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'New-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'New-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'New-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'New-MgDeviceAppMgtVppToken', 
               'New-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'New-MgDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'New-MgDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'New-MgDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Remove-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtiOSManagedAppProtection', 
               'Remove-MgDeviceAppMgtiOSManagedAppProtectionApp', 
               'Remove-MgDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Remove-MgDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Remove-MgDeviceAppMgtManagedAppPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistration', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Remove-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Remove-MgDeviceAppMgtManagedAppStatus', 
               'Remove-MgDeviceAppMgtManagedEBook', 
               'Remove-MgDeviceAppMgtManagedEBookAssignment', 
               'Remove-MgDeviceAppMgtManagedEBookDeviceState', 
               'Remove-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Remove-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Remove-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Remove-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Remove-MgDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Remove-MgDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Remove-MgDeviceAppMgtMobileApp', 
               'Remove-MgDeviceAppMgtMobileAppAssignment', 
               'Remove-MgDeviceAppMgtMobileAppCategory', 
               'Remove-MgDeviceAppMgtMobileAppConfiguration', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Remove-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Remove-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Remove-MgDeviceAppMgtVppToken', 
               'Remove-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Remove-MgDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Remove-MgDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Remove-MgDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Set-MgDeviceAppMgtManagedEBook', 'Set-MgDeviceAppMgtMobileApp', 
               'Set-MgDeviceAppMgtMobileAppConfiguration', 
               'Set-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Sync-MgDeviceAppMgtMicrosoftStoreGraphFPreBusinessApp', 
               'Sync-MgDeviceAppMgtVppTokenLicense', 'Update-MgDeviceAppMgt', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtection', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtectionAssignment', 
               'Update-MgDeviceAppMgtAndroidManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtection', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtiOSManagedAppProtection', 
               'Update-MgDeviceAppMgtiOSManagedAppProtectionApp', 
               'Update-MgDeviceAppMgtiOSManagedAppProtectionAssignment', 
               'Update-MgDeviceAppMgtiOSManagedAppProtectionDeploymentSummary', 
               'Update-MgDeviceAppMgtManagedAppPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistration', 
               'Update-MgDeviceAppMgtManagedAppRegistrationAppliedPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistrationIntendedPolicy', 
               'Update-MgDeviceAppMgtManagedAppRegistrationOperation', 
               'Update-MgDeviceAppMgtManagedAppStatus', 
               'Update-MgDeviceAppMgtManagedEBook', 
               'Update-MgDeviceAppMgtManagedEBookAssignment', 
               'Update-MgDeviceAppMgtManagedEBookDeviceState', 
               'Update-MgDeviceAppMgtManagedEBookInstallSummary', 
               'Update-MgDeviceAppMgtManagedEBookUserStateSummary', 
               'Update-MgDeviceAppMgtManagedEBookUserStateSummaryDeviceState', 
               'Update-MgDeviceAppMgtMdmWindowInformationProtectionPolicy', 
               'Update-MgDeviceAppMgtMdmWindowInformationProtectionPolicyAssignment', 
               'Update-MgDeviceAppMgtMdmWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgDeviceAppMgtMdmWindowInformationProtectionPolicyProtectedAppLockerFile', 
               'Update-MgDeviceAppMgtMobileApp', 
               'Update-MgDeviceAppMgtMobileAppAssignment', 
               'Update-MgDeviceAppMgtMobileAppCategory', 
               'Update-MgDeviceAppMgtMobileAppConfiguration', 
               'Update-MgDeviceAppMgtMobileAppConfigurationAssignment', 
               'Update-MgDeviceAppMgtMobileAppConfigurationDeviceStatus', 
               'Update-MgDeviceAppMgtMobileAppConfigurationDeviceStatusSummary', 
               'Update-MgDeviceAppMgtMobileAppConfigurationUserStatus', 
               'Update-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfiguration', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationApp', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment', 
               'Update-MgDeviceAppMgtTargetedManagedAppConfigurationDeploymentSummary', 
               'Update-MgDeviceAppMgtVppToken', 
               'Update-MgDeviceAppMgtWindowInformationProtectionPolicy', 
               'Update-MgDeviceAppMgtWindowInformationProtectionPolicyAssignment', 
               'Update-MgDeviceAppMgtWindowInformationProtectionPolicyExemptAppLockerFile', 
               'Update-MgDeviceAppMgtWindowInformationProtectionPolicyProtectedAppLockerFile'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/features/2.0/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInlgYJKoZIhvcNAQcCoIInhzCCJ4MCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCArmhJ4p9B4nK6e
# fq/EMa0KMB6OAq2elqgE/piZOC4B5qCCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGXYwghlyAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIAaKMErygk4cbRW0ajDGnyoQ
# TKticifYcaiCE5yYTlp8MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEANiEuDcHoFWuvnpxQw68VxgCLztT2YPHXTBtBdnw84rROyoVpKTQill3E
# hlwk9FQBaYks8TJ0li9er1aJvvWCNpa9e0gUkWdlg9szGRl72knptPtjGiw+g+Ug
# VRcVJsq1o7EmAM6J1JZDG729otdk7U801wvOmMNa3nSzJDOEg1EQoLpr7uWlmxJd
# JfROR9Om3ETp4opNaPIH9nJ5sk8F7GRFriNWfd5Le4xvf4XzpAhwsIy9mlqTsE7i
# MtuN7fCUkUUo42Sg9zKITsiug4rvIkLHIXTvmHcm1JZ6z7ooYJt8pkYEJ17LxMxL
# Ix+Uegut3S/Th/VIv62aAU7qsnM9l6GCFwAwghb8BgorBgEEAYI3AwMBMYIW7DCC
# FugGCSqGSIb3DQEHAqCCFtkwghbVAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFRBgsq
# hkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCDIWq3O0npBlgsB8RTwsFCnMOc5yduqg4x+5efeBOsNFwIGZLBzSdXt
# GBMyMDIzMDcyNjE5MTg1NS44OTVaMASAAgH0oIHQpIHNMIHKMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpFQUNFLUUz
# MTYtQzkxRDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
# EVcwggcMMIIE9KADAgECAhMzAAABw4tv00i/DpFdAAEAAAHDMA0GCSqGSIb3DQEB
# CwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIyMTEwNDE5MDEy
# OVoXDTI0MDIwMjE5MDEyOVowgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMx
# JjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOkVBQ0UtRTMxNi1DOTFEMSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEF
# AAOCAg8AMIICCgKCAgEAu+u86s3R/q+ikos80aD42Ym21NDOZtldNRxMFUxm4o9k
# VWkSh2c8jOCxJXwV2KFodCTxpGQs9jy5nUI+Lq/bt0HWtSYPMPPtet420gzwM1Es
# R26kbpwlBHxFY4hk3y3AH+1YKf9bhvPs7kPbXbH7gdaciteB+F7FoORt9e0D/dsB
# eG80GZAF2y6LWAj6C2mMqlafXkwbfTyQanuX65Yu+xMpyJ1fAREpuR766rePrqlE
# 0KaaeD0nqOgGrTkSZeCMDPH6OtJ00jXMwbIDyH7l4fYReIsTfzN5Gf3Uairsjea+
# KFy22lU8elnIXjoeyx3pcesH+q5arY1c6HPfeSnkeMok/gxnB7P1Mjt7I9EI9thQ
# tMvy/1SUmLG12rBR/DfheE/VJpcm/TYeoV11NfQQnl/jBbPbSRBp0HGqTIcWDpY6
# MgSdBoQET1DvpE4PX4sndNGc1wGyg45pH62ZMfUF/CzGZ7iV637RtnQFXDzTxoSE
# EkdXMdWDJG+jjxoC16lRk1xFnfkA4uoma4mKso7qvE6d27+K6yzISWQ7TjutYLKJ
# nSzNvfiNiuyv/0xxCASSARvOQ3v9cegvM/pnuU9c6s+4gmK3+5jhcvnWGQqJE0tp
# YHmk3bmmBL1gHm9TjBJz5m/8rvHM3Rw3OUhV4/wmAL32KmPR5Ubb4ww5HNGiuY0C
# AwEAAaOCATYwggEyMB0GA1UdDgQWBBQcGL7N2NdvAaK8TcLrxMTsa8aB1jAfBgNV
# HSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5o
# dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
# aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
# CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRz
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IC
# AQDd8qZbHBqdBFRDxGGwDollnRyd0WmUnjqoP+5QCH4vMPBt4umHVhJuyeRkDELk
# TWZuWqK3U1z2HnGatbnETcHUlywlH+3I7R7fU0zKYw2PLA+VawCcrnsICgE3242E
# sEC/Z0YU740NJ/xbuzrGtTEtUIiQvr2ACPJyhsPote8ItTf4uNW4Mbo1QP0tjcBK
# CgEezIC4DYUM0BYCWCmeZmNwAlxfpTliOFEKB9UaSqHSs51cH8JY0gqL3LwI9LYf
# jEO77++HY/nMqXCMi9ihUKoIp2Tfjfzdm5Ng5V+yw8+wXl29RcW4Q4CvHntNfKxT
# 9oQ3J7YBQQEHWJPg8TNR9w4B82FzmrDd8sL6ETvGux5hFcwmF+Q2rT5Ma8dYUSdC
# Sg/ihoEYUGJZnZL9nyDp1snflSVX7FpLyALzDDlHBW1CJhYVffJRoqz1D4kRooqR
# BNRaMFMPingywwbEghMheJKNoda7AGgq+1HH1afRlE+9qYW9FKMezxeQmf8gcuAu
# hr9IAXyaF9DF0PJ5f4uhzOSvIC1BkJtzF6op45UYaI7V+9X8dcwXbZJnIIAH1cjV
# O8KEChxKIkpk4Qgy0PocgUwaGWqmLWRu1hQ1WJWnQXvvBYeYDGWbj/PtSlywv6m8
# mujLepfMvJcU25KWklSP2FuNx6aOVfeje+pgbwIQIVQ1nTCCB3EwggVZoAMCAQIC
# EzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoX
# DTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC
# 0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VG
# Iwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP
# 2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/P
# XfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361
# VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwB
# Sru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9
# X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269e
# wvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDw
# wvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr
# 9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+e
# FnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAj
# BgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+n
# FV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEw
# PwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9j
# cy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3
# FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAf
# BgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBH
# hkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUF
# BzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0Nl
# ckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4Swf
# ZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTC
# j/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu
# 2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/
# GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3D
# YXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbO
# xnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqO
# Cb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I
# 6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0
# zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaM
# mdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNT
# TY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLOMIICNwIBATCB+KGB0KSBzTCByjEL
# MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
# bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWlj
# cm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEmMCQGA1UECxMdVGhhbGVzIFRTUyBF
# U046RUFDRS1FMzE2LUM5MUQxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAPEdL+Ps+h03e+SLXdGzuY7tLu7OoIGD
# MIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQG
# A1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEF
# BQACBQDoa2wtMCIYDzIwMjMwNzI2MTc1NTU3WhgPMjAyMzA3MjcxNzU1NTdaMHcw
# PQYKKwYBBAGEWQoEATEvMC0wCgIFAOhrbC0CAQAwCgIBAAICEB8CAf8wBwIBAAIC
# EbgwCgIFAOhsva0CAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAK
# MAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUFAAOBgQCVJP7Ch89C
# v1OOQK/PPxBgglPi68Jh6MLWeohs4p2q/hkE+w47fA+74M4zMVUb3+/oZ8Nd3AEg
# WNKX/TxENt3fAJom1TrhZ7tM7HrqmzEEIVRwfaeV552jszmFMtd4wytIZeyELpGW
# f0ElOD0kMo92iLL89OnAmW+bdFzhBTd4TTGCBA0wggQJAgEBMIGTMHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABw4tv00i/DpFdAAEAAAHDMA0GCWCG
# SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZI
# hvcNAQkEMSIEIM3aEG5WHIXTGZ4SgUa3oIbjPeyC4oFdbPlFFalcMly+MIH6Bgsq
# hkiG9w0BCRACLzGB6jCB5zCB5DCBvQQg0vtTm2+SSerh1KiAkwrJTALxTfJotlPc
# DZ2ZSn78KkkwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAIT
# MwAAAcOLb9NIvw6RXQABAAABwzAiBCA5wCg5xdo2Z6/t3C2ATgBxCwnMqzfKZoZj
# OV2fdQyJojANBgkqhkiG9w0BAQsFAASCAgAlRhkh6PBpnUzApeBlB0x+gE1DEuIR
# KUMNQ+77186rYfaLGVsA+a9tdVnkugaY99nhSVL8AGohomv54S/gTjW2+LyNkyyx
# 855oo/2GJsIvQNyzwn9bzhNhrj46x6AF2BxCLPGH9hZns0TGBIjbw3+ZKVLQ9GAB
# dU4YwOt0gHwKSR02GDWOXM9zTedn09P0ycFEfZP9Ws6drsnAt1hFBO+1qjYfTgGW
# nfgASeEu+ht5eqYYse7fJE3W38Ttgq/2bsOzOeSpwWk+7mt3gVy2FNzIdlrh7L0R
# CSufFRTDfywyF4cZzJ6eeFycesj2Kzb58bwhV5cX35V0I1xwYeQMzdxalYRviJgJ
# XeqKM1uY5klnHX9hmhq9d+fU0gAZmoUFTk8X/66lX3yDElgeqUn2aVaY16mQf/zF
# 1EYA6mVnUytVzBt8QkY4TPp/xUKSV3vLxkCAdD0PCcJisNEEXsMU4aq78CZFPAe0
# 0Rd65jNpXVJ6hjIJvRWKPNcLy5xZ/TtyrWM4/+syvh37W+mTSIKTMD+3M5IqibXz
# I/nftDHD57Th/H+IlG87lofdHrxHidg9ovM6MGK4yWax/VwvXHSfTEY7f9QhD4io
# LQ1q7g958oqXzyT8KzVaOlDNIg6N99/mSXDE7mgAX2AtW4q4RcODgS1LcpYFc5pT
# jMejIj02jlUPPg==
# SIG # End signature block
